### ISSUE TITLE
Null vs "" for string fields

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#110]
What’s the best practice for NULL vs “” for Rails apps with JS front ends (postgres)? Just ran into a thorny issue!

http://forum.shakacode.com/t/null-vs-for-rails-with-postgres-with-js-client-app/369 

@josiasds, @alexfedoseev, @samnang: Let's figure some best practice recommendation.

**Comment by samnang** [comment]
My take on this:

* We should never use nullable on string or boolean columns. Avoid it by `null: false, default: ""`
* For number or datetime columns could be nullable because in some scenario nil represent the missing value/input.

**Comment by justin808** [comment]
I'm OK with that. There's just no reason for it on boolean or string.

@josiasds @geoffevason Any opinions?

**Comment by justin808** [comment]
@josiasds This would be a good quick one for you to throw in the code.
