### ISSUE TITLE
Consider reversing the 3000/4000 ports 

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#116]
Since Rails is a default of 3000, we should consider switching this:

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/server.js#L54

```javascript
server.listen(3000, 'localhost', function(err) {
  if (err) console.log(err);
  console.log('Listening at localhost:3000...');
});
```

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/Procfile.dev#L1

    web: rails s -p 4000

Anybody second me on this suggestion?

**Comment by szyablitsky** [comment]
Already done this in my own project. :+1:

**Comment by josiasds** [comment]
+1 on switching this.
