### ISSUE TITLE
Demonstrate how i18N could work with webpack and rails

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#120]
> The other question I have is, how should I manage I18n? ... Is there a way to integrate Rails I18n into this React+Webpack+Rails integration?

That's a great question. I'm guessing, not having done it with this setup, that you could do something like this:

https://github.com/fnando/i18n-js#rails-app-without-asset-pipeline

We'd love to see a pull request example of how this can be done. 

![2015-10-14_16-35-12](https://cloud.githubusercontent.com/assets/1118459/10500992/e54645ee-7291-11e5-8134-1b2863c5c6e9.png)

**Comment by rstudner** [comment]
I think using i18n.js to server up the asset files from the rails side is one option, and then have the client side stub out the same method and do some sort of node/yml lookup.  i'll tinker with this and see what can be done.

**Comment by justin808** [comment]
See https://github.com/shakacode/react_on_rails/issues/212
