### ISSUE TITLE
Test out proxying to main rails server from hot module reload (webpack-dev server)

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#133]
* https://github.com/gaearon/react-hot-loader/issues/46
* https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/server.js#L30

I think we could start the hot reload server with an env var (or even start on different ports in the proc file!) and show this off.

* Port 3000 for Rails
* Port 4000 for Webpack Dev Server, proxy last
* Port 5000 for Webpack Dev Server, using proxy first

By Proxy first or last, that will determine if the callbacks in server.js or the rails server handle the API calls.

**Comment by justin808** [comment]
@necronet Would you be able to try this out in a fork?

**Comment by necronet** [comment]
I have a similar setup with using `contenBase` and seems webpack setup the proxy to point to the proper endpoints I'll do an sample on this!

**Comment by justin808** [comment]
@necronet Please create a fork and maybe we can bring this in, and if it's super cool, @robwise will put in our generator.

**Comment by justin808** [comment]
Closing this as we'll soon be changing around a few things which will address this issue.
