### ISSUE TITLE
Include pure-render-decorator

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#141]
If we're using Immutable.js, we should use the pure-render mixin. However, we're about to change to ES6 classes, so this seems to fit the bill.

```javascript
import {Component} from 'react';
import pureRender from 'pure-render-decorator';

@pureRender
class Test extends Component {
  render() {
    return <div></div>;
  }
}
```

* https://facebook.github.io/react/docs/pure-render-mixin.html
* https://github.com/felixgirault/pure-render-decorator
* https://www.npmjs.com/package/pure-render-decorator
* [React.js Conf 2015 - Immutable Data and React](https://www.youtube.com/watch?v=I7IdS-PbEgI)

CC: @alexfedoseev @rstudner @robwise

**Comment by robwise** [comment]
Cool! It was unclear from the React documentation, but if you use Immutable objects (which we are), do you still need to do the `forceUpdate()` thing because of the shallow object introspection problem? I couldn't tell if they meant you didn't need it with Immutable objects or just that Immutable objects would make `forceUpdate()` run faster.

**Comment by justin808** [comment]
@robwise I don't think forceUpdate() is necessary. It should just work.

**Comment by justin808** [comment]
@mamute want to give this a try?

**Comment by mamute** [comment]
sure :+1:

**Comment by mamute** [comment]
Hey guys, how can I check if a component is rendering faster or any other result of pure-render implementation?

**Comment by justin808** [comment]
@alexfedoseev @josiasds @alexfedoseev Should we be including the pure render mixin like this: https://christianalfoni.github.io/react-webpack-cookbook/Javascript-next.html

**Comment by robwise** [comment]
@justin808 @mamute @alexfedoseev 

For performance checking, see https://facebook.github.io/react/docs/perf.html
