### ISSUE TITLE
Use CSS Modules?

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#142]
Will CSS go the way of JavaScript with modules?

And if already using React + Webpack?

https://www.youtube.com/watch?v=aIyhhHTmsXE

* http://glenmaddern.com/articles/css-modules
* https://github.com/css-modules/css-modules
* https://github.com/gajus/react-css-modules
* https://css-modules.github.io/webpack-demo/

![2015-10-30_21-34-45](https://cloud.githubusercontent.com/assets/1118459/10861884/3de80074-7f4f-11e5-883a-700ddac73794.png)

Also posted here: http://forum.shakacode.com/t/css-modules-if-using-react-and-webpack/394

**Comment by justin808** [comment]
@alexfedoseev @jbhatab @samnang @robwise @josiasds @mapreal19 @dylangrafmyre Worth considering!

**Comment by jbhatab** [comment]
This blog was great on ICSS. http://glenmaddern.com/articles/interoperable-css. The video should be coming out soon, it was a great talk.

I'm definitely on board.

**Comment by robwise** [comment]
The cool thing about doing it this way is that you can put the styling for your "bundle" (here meaning a folder within `client/app/bundles`) with the actual bundle, which is cool for organization as well as for modularity (meaning it's easier to extract the component for reuse components across apps, if you wanted to).

**Comment by rstudner** [comment]
I've used this css bundle technique. It is *very* handy

**Comment by justin808** [comment]
Had great chat with @alexfedoseev. Looks like this can work. @jbhatab, you'll be proven right about creating the CSS within Webpack. Here's the steps:

- [ ] Update the bootstrap-sass-loader so that it wraps the resulting sass in `:global {}`. See https://github.com/shakacode/bootstrap-sass-loader/issues/36
- [ ] We'll need a new webpack config file to build the extracted CSS along with fingerprinting the corresponding assets, written to the `/public/` directories (what's the directory structure within `/public`?). 
- [ ] Update [assets.rake](https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/lib/tasks/assets.rake) so that it adds another line, like this, plus updating the clobber task:
```
  desc "Compile assets with webpack"
  task :webpack do
    sh "cd client && npm run build:client"
    sh "cd client && npm run build:server"
    sh "cd client && npm run build:css_assets"
  end
```

**Comment by justin808** [comment]
@alexfedoseev and I are working on: https://github.com/shakacode/bootstrap-loader/tree/alex/bootstrap-4. We'll be adding CSS modules here shortly.

**Comment by justin808** [comment]
Done! this is in master!
