### ISSUE TITLE
Consider isomorphic-fetch

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#143]
Redux docs recommend:
- https://github.com/matthew-andrews/isomorphic-fetch

We're using axios
- https://github.com/mzabriskie/axios

Probably no reason to switch, but just noticed the recommendation from the redux docx.

@alexfedoseev What's your call?

**Comment by alexfedoseev** [comment]
Let's leave this open. Because of "no reason to switch" it's low priority, so let's review it in a month or so.

**Comment by justin808** [comment]
Any more thoughts on this one? I'd like to put in a utility method in react-on-rails npm that encapsulates one of these libraries with the meta tag for the CRSF with Rails. @jbhatab @rstudner @alexfedoseev

**Comment by justin808** [comment]
Given the overwhelming popularity of isomorphic-fetch now, and given that react-native uses "fetch", let's switch.

* https://www.npmjs.com/package/isomorphic-fetch
* https://www.npmjs.com/package/axios

We're also going to create a ReactOnRails helper that does the CSRF part.

CC: @dzirtusss
