### ISSUE TITLE
Need to refactor the README.md

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#146]
It's too long and too scattered.

We can create docs directory with short notes.

We should update this once we push out v1.0 of react_on_rails.

CC: @robwise

**Comment by robwise** [comment]
@justin808 definitely agree with the problem, but I think the solution should be a wiki and not the docs folder as the former seems to be a more popular convention as @jbhatab pointed out.

**Comment by justin808** [comment]
1. The problem with the wiki is that it doesn't force us to review what goes in, and wikis get hopelessly outdated and nobody ever cleans them up.
2. Even more so for the gem, it's critical that the docs match up with the code, so having version tags and branches is critical.

**Comment by muloka** [comment]
:+1:

**Comment by justin808** [comment]
This was done by @Judahmeek!
