### ISSUE TITLE
Miscellaneous Cleanups Per react_on_rails generator examples

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#154]
See these PRs: https://github.com/shakacode/react_on_rails-generator-results-v1.0.3/pulls (might have to look at most recently closed ones).

There's many small details that we're doing in the generators that are not done with this tutorial:

- [ ] Convert to a bundles directory structure, updating the webpack configs
- [ ] Convert to Puma from unicorn
- [ ] Convert `::` bindings for react callbacks to use _.bindAll(this, ['_func1', '_func2'] where _func1, etc are the event handlers.

**Comment by robwise** [comment]
also the loggerMiddleware should just use `JSON.stringify` as in the generators

**Comment by josiasds** [comment]
@justin808 Is anyone working on this? Maybe @mamute could give it a try.

**Comment by mamute** [comment]
I can certainly look into it

**Comment by justin808** [comment]
This is the most relevant PR to compare to: https://github.com/shakacode/react_on_rails-generator-results-v1.0.3/pull/114/files. @mamute, possibly you can coordinate with @thiagoc7.

**Comment by thiagoc7** [comment]
@justin808, Convert to Puma from unicorn on PR #160

**Comment by justin808** [comment]
@thiagoc7, @josiasds, @mamute Please coordinate on bring over the latest suggestions. 

Here's redux server rendering:
https://github.com/shakacode/react_on_rails-generator-results/pull/124/files

I think the heroku changes are done by @thiagoc7 already.
https://github.com/shakacode/react_on_rails-generator-results/pull/130/files

As you go through these, please comment in the PRs of the changes in terms of what the generators could/should be doing better, and any other useful information.

I did quite a bit of that here:
https://github.com/shakacode/react_on_rails-generator-results/pull/123/files

**Comment by mamute** [comment]
Convert :: bindings for react callbacks to use _.bindAll on PR #167

**Comment by justin808** [comment]
From @robwise:

> also the loggerMiddleware should just use JSON.stringify as in the generators


Rob, can you help @josiasds @mamute out with this one.

**Comment by robwise** [comment]
@josiasds @mamute basically, we were using a loop to go through the Immutable object and extract a bunch of stuff out to be printed to the console. That's completely unnecessary, because you can just call `JSON.stringify(myImmutableObject)` and forget all of that nonsense.

Here is the relevant example from the gem: https://github.com/shakacode/react_on_rails/blob/master/lib/generators/react_on_rails/templates/redux/base/client/app/lib/middlewares/loggerMiddleware.js

**Comment by mamute** [comment]
@robwise this will make the JS object be printed as a string… is that what we expect?

**Comment by robwise** [comment]
@mamute Yep! We could also just log the object directly, but I was just simplifying the code that was already there when I first got on the project, and that's what it was doing.
