### ISSUE TITLE
AjaxCounter

### ISSUE THREAD

**Issue by thiagoc7** [shakacode/react-webpack-rails-tutorial#156]
Hello guys, thanks for this awesome repo.

Maybe it's a silly question... but I didn't understand why use AjaxCounter functions to track loading state.
On redux [tutorial](http://redux.js.org/docs/advanced/AsyncActions.html) they use `isFetching`, which feels like a simpler solution to me.

Is there any reason for this design choice that I didn't get?
Or would you accept a `PR` implementing this tutorial's design?

Thanks again!

**Comment by robwise** [comment]
@alexfedoseev is probably the best guy for answering that

**Comment by justin808** [comment]
Yes, a PR would be FABULOUS! @thiagoc7 the reason we had the counter was that we considered showing the number of in-flight ajax requests, and if there are multiple ones, how will you know when no more are in-flight?

**Comment by justin808** [comment]
@thiagoc7 Let us know if you would like an invite to our slack room.

**Comment by thiagoc7** [comment]
Hi @justin808!
Sure, I would like an invite for slack, thanks! My email is thiagobocorrea@gmail.com.

About the counter, what I don´t understand is why you need to know how many ajax requests are in-flight. If the goal is showing a spinner, just a `boolean` isn´t enought?

My idea is to track both `isFetching` (for a spinner) and `isSaving` (for submit button).
I´ll create a PR anyway, so you guys can easely check if it´s a good idea or not.

Cheers!

**Comment by thiagoc7** [comment]
PR #158
