### ISSUE TITLE
Question with assets.rake

### ISSUE THREAD

**Issue by huoshiqiu** [shakacode/react-webpack-rails-tutorial#172]
When you are deploying **assets:precomile** I have a question how do you run the NPM command directly, 
because I look up how to run NPM through the SSH command, as if you need to set the environment variable, these problems are derived from the time I have been deployed with error **no NPM command** 

[assets_file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/lib/tasks/assets.rake)
need some help, thanks

**Comment by justin808** [comment]
Be sure that you have current versions of nvm and npm installed and are using at least 5.0 of node.

Do not use Babel 6 yet. Stick with Babel 5 for now.
