### ISSUE TITLE
Including Font Awesome?

### ISSUE THREAD

**Issue by nicholasalanbrown** [shakacode/react-webpack-rails-tutorial#173]
HI -

I'm using this terrific boilerplate and have tried including Font Awesome both through the ```font-awesome-rails``` package with an ```@import``` statement in ```application.css.scss``` and as an npm module, but can't get either implementation to work. Is this  some weirdness caused by the modified asset pipeline?

Thanks!

**Comment by justin808** [comment]
Hi! We're in the process of totally reworking the process for inclusion of Sass in Webpack + Rails projects in the next few weeks. See https://github.com/shakacode/react-webpack-rails-tutorial/issues/162.

I'd say that it's critical to adjust this file: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/assets/stylesheets/_bootstrap-variables-customization.scss

You should probably install font awesome from the gem for rails, and from npm for the hot-reload server.

In the **very** near future, we'll do all the sass/css from webpack, so you'll just use npm. If you can, please try out using the npm font-awesome here: https://github.com/shakacode/bootstrap-loader-css-modules-example. Please do a PR and we'll make sure it works from npm. This is a user case we want to support. CC: @alexfedoseev
