### ISSUE TITLE
Allow running in development mode without the WebpackDevServer to vend assets

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#178]
Should we allow the standard, `webpack -w` mode for development? A possible reason is to do development testing with what the specs see.

I discussed this with @alexfedoseev.

Let's have an ENV variable configure if we're using the hot reloading way of using port 3500 for assets or using the standard way of simply loading the webpack compiled file.

How about an ENV variable called:

```
RAILS_HOT_RELOAD_ASSETS=TRUE
```

Some questions: 

1. Do we only accept TRUE or other truthy values to turn this ON?
2. Should we simply have a different foreman file for this?
3. If the ENV value is not specified, do we default to off? or on?

-----
Another option:

We could do something smart, like check for the server running, and, if not, then assume that we should fallback to the pre-compiled file. We can be smart and once we detect the server is not running, don't check within so many minutes from the last request, so we don't slow down ever request. But maybe it's super fast to check this.

  ```erb
  <%= env_stylesheet_link_tag 'application_prod', 'application_dev', media: 'all', 'data-turbolinks-track' => true  %>
  <%= env_javascript_include_tag nil, 'http://localhost:3500/vendor-bundle.js' %>
  <%= env_javascript_include_tag nil, 'http://localhost:3500/app-bundle.js' %>
  <%= env_javascript_include_tag 'application_prod', 'application_dev', 'data-turbolinks-track' => true %>
  ```

**Comment by justin808** [comment]
Almost done: https://github.com/shakacode/react-webpack-rails-tutorial/pull/203

**Comment by robwise** [comment]
@justin808 I like that env variable name much better. I think the check for the server running or not, while slick, might actually be a little too slick. If I want to use hot reloading, but my server isn't running, I want to get a really obvious error, not a silent fallback to static assets (or vice versa, if I specify static assets, I don't want to silently use hot reloading instead).

**Comment by justin808** [comment]
@robwise The objectives are:

1. Ensure bundles created before starting any test. This means the webpack bundles are newer than the newest JS file. If Webpack watch is running, it's a safe bet we don't need to generate the file.
1. Minimal chance of forgetting to do #1.

**Comment by robwise** [comment]
@justin808 If tests should be running off of static bundles, if we have Webpack running in development mode, don't we still need to generate the bundles?

**Comment by justin808** [comment]
We have the https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/Procfile.spec

and this line: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/Procfile.dev#L15

Basically, the flow should be that if the developer wants to run Rails tests, then we should be running with the webpack watcher (either static dev or the spec one).

**Comment by justin808** [comment]
@robwise so yes, dev.static does generate the files. dev.hot does not!

**Comment by justin808** [comment]
This was done!
