### ISSUE TITLE
Update the webpack config for production assets to gzip

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#179]
For production deployment, we should gzip any assets. And only for production.

CC: @alexfedoseev

**Comment by justin808** [comment]
@alexfedoseev should we still do this?

**Comment by alexfedoseev** [comment]
@justin808 I thought pipeline handles this, no?

**Comment by justin808** [comment]
I'm pretty sure it can. I used to use the heroku deflater gem.

https://github.com/romanbsd/heroku-deflater

**Comment by alexfedoseev** [comment]
I remember I was investigating the things I need to do to replace AP and gzip was in the list that is handled by pipeline.
