### ISSUE TITLE
Latest react-webpack-rails-tutorial has error finding /__webpack_hmr

### ISSUE THREAD

**Issue by thewoolleyman** [shakacode/react-webpack-rails-tutorial#182]
Hi,

I'm trying to get my bearings by running latest master (https://github.com/shakacode/react-webpack-rails-tutorial/commit/814671df8953ecbf8756ab9474d912515cb36217) of https://github.com/shakacode/react-webpack-rails-tutorial

I'm following the README.md, and everything seems to work when I run `bundle exec foreman start -f Procfile.dev`.

But, I get this error from the rails server:

    20:22:43 rails.1               | Started GET "/__webpack_hmr" for ::1 at 2015-12-19 20:22:43 -0700
    20:22:43 rails.1               |
    20:22:43 rails.1               | ActionController::RoutingError (No route matches [GET] "/__webpack_hmr"):

I'm assuming that something isn't configured properly to hit the hot reload server running at port 3500 in this case, but I'm not sure if that's the issue, or how to fix it.

Thanks,
-- Chad

**Comment by justin808** [comment]
@thewoolleyman You don't hit 3500 directly. That's done by localhost:3000.

I just did a fresh try, and the app is working as expected.

Both ports 3000 and 4000 work.

Check out https://github.com/justin808/justin808-dotfiles/blob/master/zsh/rails.zsh

I use `pgkk` all the time to kill rogue processes.

**Comment by thewoolleyman** [comment]
Ah ok, it was another browser tab still making requests.  Thanks!
