### ISSUE TITLE
Consider a variation of the simple example with react-refetch

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#184]
This seems relatively popular: https://github.com/heroku/react-refetch

This would be a nice alternative to showing redux vs. simple. This is in between.

@geoffevason @robwise What are your thoughts on this one?

@mamute Are you interested in giving this a try?

**Comment by robwise** [comment]
@justin808 I've been reading the docs trying to wrap my head around it. It seems like this relies heavily upon React Router to determine when it needs to refetch (it uses the change of URL as well as the params in the URL to know when and what to refetch)? I'm always open to new tech I guess.

**Comment by mamute** [comment]
@justin808 sure :+1:

**Comment by justin808** [comment]
> however, if your application is mostly fetching and rendering read-only data from a server, it can over-complicate the architecture to fetch data in actions, reduce it into the store, only to select it back out again.

This example shows data entry, so closing this one.
