### ISSUE TITLE
Brainstorming Ideas

### ISSUE THREAD

**Issue by thewoolleyman** [shakacode/react-webpack-rails-tutorial#190]
Not really an issue, just throwing out some ideas for thought.

I'm really liking the react_on_rails approach, and would like to see it get more mature.  It seems to make a lot of things easier than having a more standalone/separate React app/repo that takes more work to integrate with the Rails API/asset pipeline and CI/build workflows.

I've found some other cool things it facilitates I'd like to eventually share too.  E.g.:

* I have all my server (server rendered, express dev, and local prod) and test (rails, capybara, and mocha) envs all loading and using the same fixture data from Rails fixture files generated via fixture_builder and factory_girl.

* I think it is especially well suited to single page apps, that can inject all the required initial state on the initial server rendered component.  I'm using a flat initial state from a single "Page" controller action that just injects a flat state with arrays of model types.  Then, I use humps + normalizr + Immutable to turn this into the initial state on the store.

* Just starting this, but I'm going to try to do authentication via Oauth + Json Web Tokens as described [here](http://fredguest.com/2015/03/06/building-a-stateless-rails-api-with-react-and-twitter-oauth/), but with some changes for a single-page non-routed/non-api-access app.

* I'm also hoping to use Rails 5 ActionCable to handle most of the client-server communication from Redux actions, and avoid having to do much (or any) REST api calls (and thus also avoid having to implement the REST API in rails).  I'm hoping this fits well with the flat array-of-model-types API normalized immutable state structure described above.  Haven't even started this, we'll see how it works out - ActionCable just got moved into Rails so it's probably pretty bleeding edge.

This is all happening in https://github.com/deploysage/deploysage if you want to follow along...

**Comment by robwise** [comment]
@thewoolleyman This is totally awesome, please keep us updated!

**Comment by justin808** [comment]
@thewoolleyman Can we close this ticket? Great info...I want to keep the open tickets to only those that we're working on.

**Comment by thewoolleyman** [comment]
definitely.
