### ISSUE TITLE
Production Build

### ISSUE THREAD

**Issue by tleish** [shakacode/react-webpack-rails-tutorial#196]
What is the process for building assets and deploying to production?  I tried rake assets:precompile and then rails s, but this didn't work.  Is foreman required is production also?

**Comment by justin808** [comment]
@tleish The project deploys as-is to heroku. You can see it at http://www.reactrails.com.

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/docs%2Fheroku.md

This file is key: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/lib%2Ftasks%2Fassets.rake
