### ISSUE TITLE
Need better docs for CSS modules and howto for static images/fonts

### ISSUE THREAD

**Issue by jamesmccann** [shakacode/react-webpack-rails-tutorial#197]
Wondering if there are any good ideas and/or best practice techniques for serving images/fonts in a Rails/Webpack bundle configuration. At present I have a React app being bundled with Webpack into `assets/javascripts`. CSS Modules are being handled inline using Webpack's css-loader in modules mode, and my output bundle is deployed to `app/assets/javascripts` and served via the Asset Pipeline.

I'm looking for a tidy solution for handling images. I would like to be able to reference the images in my JS/CSS before being bundled by Webpack. One possible solution I stumbled upon was using [file-loader](https://github.com/webpack/file-loader) to emit the image files into the bundle location, which might be able to give something like the following:

```
   |-app
   |---assets
   |-----images
   |-------daa9b80bc018404d6a944c220823751d.png <--- exported by file-loader
   |-----javascripts
   |-------bundle.js
   |-webpack
   |---assets
   |-----images
   |-------logo.png
   |-----javascripts
   |-------index.js <--- references webpack/assets/images/logo.png
```

And the image is then served by Rails. Has anyone tried this and had any luck with a solution?

**Comment by justin808** [comment]
We're doing it with CSS modules. We do plan to document this at some point. If anybody wants to submit a PR with a new file in the /docs directory, that would be great.

https://github.com/shakacode/react-webpack-rails-tutorial/blob/ca98a447aefb89f6ca86b3003e0580c0e1c39ecb/client/app/bundles/comments/components/CommentScreen/CommentScreen.jsx#L48

```js
import css from './CommentScreen.scss';

export default class CommentScreen extends BaseComponent {

  render() {
    return (
            <a href="https://twitter.com/railsonmaui">
              <div className={css.twitterImage} />
              Rails On Maui on Twitter
            </a>
}
```

https://github.com/shakacode/react-webpack-rails-tutorial/blob/1ece3666e9c6cf4a20627a28a49d68c4acc2fe03/client/app/bundles/comments/components/CommentScreen/CommentScreen.scss#L14

```scss
.twitterImage {
  background: url('./images/twitter_64.png') no-repeat;
  height: 64px;
  width: 64px;
}
```

And webpack config:
https://github.com/shakacode/react-webpack-rails-tutorial/blob/ca98a447aefb89f6ca86b3003e0580c0e1c39ecb/client/webpack.client.rails.build.config.js#L38

```js
// You can add entry points specific to rails here
config.entry.vendor.unshift(
  'bootstrap-loader/extractStyles'
);

config.module.loaders.push(
  {
    test: /\.scss$/,
    loader: ExtractTextPlugin.extract(
      'style',
      'css?minimize&modules&importLoaders=3&localIdentName=[name]__[local]__[hash:base64:5]' +
      '!postcss' +
      '!sass' +
      '!sass-resources'
    ),
  },
 );

```

**Comment by tmobaird** [comment]
I know this issue is a bit older, but this has been covered fairly well in the React on Rails docs [Rails Assets](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/rails-assets.md) and [Using Webpack bundled assets with the Rails Asset Pipeline](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/rails-assets-relative-paths.md). @justin808 do you think these docs would suffice? Or is an example of using assets in the JS needed? (I believe there's already an example using images in the CSS)

**Comment by justin808** [comment]
@tmobaird Thanks for mentioning this. Maybe some points in the docs directory or readme here would we be great.

**Comment by tmobaird** [comment]
@justin808 good idea! I will find a place somewhere in the docs and readme to put those reference points.

**Comment by justin808** [comment]
This is going to change with Webpacker. @tmobaird Let me know if you want to get involved.

**Comment by tmobaird** [comment]
@justin808 I'd love to help out with this! Thanks for looping me in. Should I send a request to join the Slack team?

**Comment by justin808** [comment]
@tmobaird I sent you a slack invite!

**Comment by tmobaird** [comment]
@justin808 thanks!

**Comment by m5rk** [comment]
Is there any guide for how to use CSS Modules with React on Rails?

**Comment by justin808** [comment]
@m5rk CSS modules are not specific to React on Rails. Let me know if you have any other questions.
