### ISSUE TITLE
Update to Sprockets v3

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#200]
If I update to Sprockets v3, I cannot run

```
foreman -f procfile.rails
```

I get an error of a missing file.

This is not an issue with v2 of sprockets.

**Comment by justin808** [comment]
@mamute Any chance you want to take a look? @thewoolleyman, @martyphee?

**Comment by mamute** [comment]
Yes! I can take a look :+1:

**Comment by justin808** [comment]
See https://github.com/shakacode/react_on_rails/issues/170

@mamute Any progress on this one in the past week?

**Comment by mamute** [comment]
@justin808 not much. resuming now

**Comment by justin808** [comment]
@mamute is this still an issues?

**Comment by justin808** [comment]
We've had Sprockets v3 for a while now.
