### ISSUE TITLE
NPM Install

### ISSUE THREAD

**Issue by mchepesiuk** [shakacode/react-webpack-rails-tutorial#201]
Following the instructions to set up the app: after 'bundle install', I run 'npm install', but the I encounter a syntax error that breaks the install - looks like this: 

![screen shot 2016-01-17 at 3 54 40 pm](https://cloud.githubusercontent.com/assets/12957345/12379916/a61272bc-bd32-11e5-95a3-1c9c29f72be0.png)

Basically, I can't run the app because I can't install the appropriate npm. Please help.

**Comment by justin808** [comment]
try rm -rf /client/node_modules

and re-run npm i

**Comment by mchepesiuk** [comment]
No that doesn't work.

**Comment by justin808** [comment]
Mac OS? Try reinstalling nvm and node 5. Create a fresh directory to git clone the repo.

**Comment by mchepesiuk** [comment]
still getting a problem with the 'sleep' package

**Comment by robwise** [comment]
@mchepesiuk it says you don't have any version of React or ReactDOM installed?

**Comment by mchepesiuk** [comment]
Geeze, haha, you're right.

Goes to show I need to read my error messages carefully!

Thanks.

**Comment by justin808** [comment]
The art of avoiding Yak Shaving:

http://forum.shakacode.com/t/avoiding-yak-shaving/465
