### ISSUE TITLE
Install the https://github.com/lodash/babel-plugin-lodash

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#204]
https://github.com/lodash/babel-plugin-lodash will save some of the deploy size. 

See https://github.com/shakacode/react_on_rails/issues/206

**Comment by robwise** [comment]
That looks awesome

**Comment by justin808** [comment]
This is being tried in #234. We should wrap this one up.

**Comment by justin808** [comment]
I'm going to try to look at this over the weekend: https://github.com/shakacode/react-webpack-rails-tutorial/pull/232/files.

**Comment by justin808** [comment]
Closing this one for now. We'll want to check on this when we update to webpack 2.

**Comment by robwise** [comment]
with webpack2 it tree shakes anyway so I think you don't need to bother? Not sure tho
