### ISSUE TITLE
Loading assets on the server-side

### ISSUE THREAD

**Issue by dmitry** [shakacode/react-webpack-rails-tutorial#206]
Is there are any possibility to load an image and put it into the react component on the server-side?

**Comment by justin808** [comment]
@dmitry I don't understand the question. Server rendering simply generates DOM tags for react.

**Comment by dmitry** [comment]
I found there are no solutions to load hashed images. For example with such webpack config:

```
        {
          test: /\.(jpe?g|png|gif|svg)$/,
          loader: 'url-loader?name=[sha512:hash:base64:7].[ext]&limit=512'
        },
```

Will generate a compressed images with a hashed postfix file names in form of `[name]-[hash].[ext]` (`image.jpg` will become `image-ac6201dc`). I found there are no solution at the moment to insert an `img` tag with newly generated file into `src`.

Can we discuss how to deal with such cases?

**Comment by justin808** [comment]
@dmitry Maybe you can build a small sample app? I'm not sure what your objective if.

**Comment by dmitry** [comment]
@justin808 objective is simple: to show the image in the `img` tag from the assets path.

**Comment by justin808** [comment]
How does this differ to what are doing for background images with CSS? I.e., can you use a div with a background image?

**Comment by dmitry** [comment]
CSS files are compiled with a webpack and all the images are inlined or has a prepared link to a newly generated file. Sometimes you just need to use `img` files, instead of CSS background style rule to be indexed by the search engine, or because page may be printed out.

**Comment by justin808** [comment]
@dmitry If you want the assets to be from the Rails server, then you'll have to do a bit of research on how to make this work with the asset pipeline. However, it would be simpler to just place the assets under the public directory and to use the corresponding relative path in your JS code.

I've found it best to use assets stored in Rails for CSS backgrounds, and for other, dynamic images, I load those from something like S3.

Feel free to comment more or ask me for a slack invite to our private slack room.

**Comment by jDeppen** [comment]
I was able to get `<img src={require('./images/blah.jpg')} />` working with webpack while avoiding server/client differences:
```
(client) ctid="58"><img src="http://localhost:350
(server) ctid="58"><img src="6311fed198575e3a4c4e
```
Setting `output.publicPath` in webpack.server was the key for my setup (always using HOT with dev).
```
publicPath: devBuild ? `http://localhost:${hotRailsPort}/` : '/assets/'
```
