### ISSUE TITLE
React Demo and Simple React are broken

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#207]
![2016-01-23_19-40-31](https://cloud.githubusercontent.com/assets/1118459/12534345/4b6542f0-c209-11e5-965b-2149f736b26e.png)

React Demo and Simple React links are broken and CI passes. Nothing is rendered for those links in production.

CC: @robwise @geoffevason @yorzi @mamute @josiasds 

If anybody can take a look at this, I'd super appreciate it.

This is reproducible both on heroku and locally.

There are no console errors.

It might be related to turbolinks and the way we render react components when we get a page loaded event.

**Comment by justin808** [comment]
https://github.com/shakacode/react_on_rails/pull/221 fixes the issue.

**Comment by mamute** [comment]
@justin808 I've tested locally and your fix is working great, but there is another bug. No comment is been added since the CSRF token sent in the headers is incorrect. This was fixed id #209

**Comment by justin808** [comment]
Fixed a while back.
