### ISSUE TITLE
Layout.jsx not inheriting from BaseComponent

### ISSUE THREAD

**Issue by JamesWatling** [shakacode/react-webpack-rails-tutorial#211]
Hi @alexfedoseev,

I was just talking with @justin808 going over this tutorial, and we weren't quite sure if it was intentional that the `Layout.jsx` file extends `React.Component` rather than the `BaseComponent` that we defined in `lib`?

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/app/bundles/comments/layout/Layout.jsx#L6

Thanks, keep up the amazing work!

**Comment by alexfedoseev** [comment]
Hi @JamesWatling, looks like we just forgot to change this. It'd be great if you can submit PR w/ this small fix. Thanks!
