### ISSUE TITLE
Create a simple boilerplate project

### ISSUE THREAD

**Issue by superplussed** [shakacode/react-webpack-rails-tutorial#212]
Hello, I'm currently working on this and want to make sure it hasn't been done yet.  But I'm paring the project down to the simplest form of the "React Router Demo" so that it will be a good jumping off point for new projects.

**Comment by justin808** [comment]
@superplussed It would be more helpful if you could help us: https://github.com/shakacode/react_on_rails/labels/help%20wanted

We'd like to get this into the generator if possible. We'd have an option for --react-router.

More importantly, we'd like to get CSS module support into the generators.
