### ISSUE TITLE
Need to try out v5 of Turbolinks

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#219]
https://rubygems.org/gems/turbolinks/versions/5.0.0.beta1

@alexfedoseev I need some advice on what is breaking in our own app with regards to Turbolinks and how we can make a simple reproduction case here.

**Comment by aaronvb** [comment]
We'll need to update the event listeners with Turbolinks 5. ie: `page:change` to `turbolinks:render`

https://github.com/turbolinks/turbolinks/tree/docs#observing-navigation-events

After making those changes I was able to get the examples working.

**Comment by justin808** [comment]
@aaronvb It would be fabulous if you could add a PR to react_on_rails to support this!!!!

**Comment by aaronvb** [comment]
@justin808 Sure thing, I'll be able to start work on this tonight. I have already switched to Turbolinks 5 (from 3) in one of my projects. I'll also need to make it backward compatible with 3.

**Comment by aaronvb** [comment]
This file will need to be updated in the tutorial once you switch over to Turblinks 5. The react_on_rails gem will handle the rest.

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/app/assets/javascripts/rails_startup.js#L1

```javascript
$(document).on('ready page:load', function () {
```

```javascript
$(document).on('ready turbolinks:load', function () {
```
