### ISSUE TITLE
Add example of React-Native client

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#22]
Any thoughts on how to incorporate react-native into this tutorial?

http://facebook.github.io/react-native/

**Comment by muloka** [comment]
Not sure I follow. You'd like to see how to use React Native with a React / Rails Backend?

**Comment by justin808** [comment]
@muloka Yes. Have a react-native client talking to the same Rails server.

**Comment by justin808** [comment]
https://github.com/shakacode/react-native-tutorial
