### ISSUE TITLE
Update to Rails 5

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#220]
Since Rails 5 is getting close to shipping, let's move this to Rails 5 and see what changes.

**Comment by justin808** [comment]
@jbhatab @yorzi @aaronvb Any of you want to try updating to v5 Rails?

**Comment by thiagoc7** [comment]
Hi @justin808, I have two questions:
- the generator is working for you with rails 5?
for me it's not. After sometime without response, and `cmd + c`:
![image](https://cloud.githubusercontent.com/assets/6671184/13036983/efc93838-d35c-11e5-82eb-efd28b8ce6f4.png)

- don't you think that we need to integrate `action cable` on this repo? Show how to use it with react / redux. This is the main new feature, and I think the tutorial wouldn't be complete without it.

Thanks!

**Comment by justin808** [comment]
Can you help? We'd love to support Rails 5 ASAP!!

**Comment by thiagoc7** [comment]
There is a problem with spring, as on [dhh´s demo](https://medium.com/@dhh/rails-5-action-cable-demo-8bba4ccfc55e#.bm94s8xgo).
If I generate rails with `--skip-spring` it works.

I´ll try to update this repo for rails 5, and see how it works.

**Comment by aaronvb** [comment]
@justin808 I'll be able to put some time into testing this with Rails 5 this week.

**Comment by justin808** [comment]
@aaronvb Any word? Maybe give this to somebody else?
