### ISSUE TITLE
Make the header a React/Redux component

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#221]
By having the header be a React/Redux component and it listening to the same Redux store, we can show a message count indicator.

![2016-02-08_10-42-46](https://cloud.githubusercontent.com/assets/1118459/12895557/e517de18-ce51-11e5-9b74-53ec750fa54b.png)

**Comment by lupuszr** [comment]
@justin808 I'm interested to help on this one, but it would be great if you could explain what did you mean by the following: "not using redux, so keep same old header or add some change to make message counter update". If I understood the task correctly then one possible way to archive this is  to update the layouts/application.htm.erb to check for the routes which resolves common rails or the view with simple react component, viz. 
```ruby
  <% if ![simple_path, comments_path].each{ |x|  break if request.path.include?(x)} %>
     <!-- current header implementation ... -->
  <% else %>
      <!-- react/redux header component with shared store -->
  <% end %>
```

**Comment by justin808** [comment]
@lupuszr Send me your email and I'll send you an invite to our slack room.

Basically, what I mean is this:

You have a rails layout where the header is a react/redux component.

The body might be another react/redux component, but it also might be a standard rails page.

**Comment by justin808** [comment]
@lupuszr We can use one header for the app. One issue with the tutorial is that that some of the links go to places not using redux, so you're right, just have an if statement pick the header!

**Comment by justin808** [comment]
See #239.
