### ISSUE TITLE
jquery-ujs not working

### ISSUE THREAD

**Issue by SqueezedLight** [shakacode/react-webpack-rails-tutorial#225]
It seems i can't get ```jquery-ujs``` to work in a fresh react on rails installation.
The following tag does not fire a confirmation window:

```<a data-confirm="Please confirm..." href="/myLink">delete</a>```

```jquery-ujs``` is loaded and prevents following the link when clicked. But the confirmation window does not show up. No errors or warning. Therefore hard for me to debug.

Can anyone else reproduce this problem?

Thank in advance.

**Comment by justin808** [comment]
@SqueezedLight I think this more appropriate for http://forum.shakacode.com/.

Did you compare your jquery-ujs setup with the one here?

Can you create a simple test repo that shows this issue? or modify the tutorial to show this issue? I'd suggest just adding the confirm to an element.

BTW, if you're dynamically adding the anchor via JS code, and there's no page load, I think jquery-ujs might not install the event handler.
