### ISSUE TITLE
Pass in props as an object

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#227]
We're passing in an array here as "props"
https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client%2Fapp%2Fbundles%2Fcomments%2Fstore%2FcommentsStore.js#L8

But props should be 

```js
{
comments: '<the comments array>'
}
```

This requires updating the jBuilder.

@jbhatab knows what to do on this one.

**Comment by alexfedoseev** [comment]
:+1:

**Comment by marz0** [comment]
This looks to be fixed by #246 correct?

**Comment by justin808** [comment]
YES! Thanks for catching this!

**Comment by justin808** [comment]
@marz0 Let me know if you want a slack invite.

**Comment by marz0** [comment]
@justin808 I'd be happy to join in on slack

**Comment by justin808** [comment]
@marz0 Please email me so I have your email!
