### ISSUE TITLE
Hot Module Reload doesn't work for reducers

### ISSUE THREAD

**Issue by exciton** [shakacode/react-webpack-rails-tutorial#236]
I'm using this tutorial to help set up hot module reloading in a React + Redux + Rails app I'm building.

It works fine to test changes to React components and styles, but fails when trying to make changes to reducers.
You get the following log messages:
[WDS] App hot update...
[HMR] Checking for updates on the server...
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
[HMR]  - 181
[HMR] Nothing hot updated.
[HMR] App is up to date.

Any idea how this can be fixed?

You can try this out by running the Procfile.dev in the tutorial, visiting localhost:3000 then editing one of the reducer files.

**Comment by exciton** [comment]
Just got this working by following notes here: 
https://github.com/erikras/react-redux-universal-hot-example/issues/44#issuecomment-132260397

Insert something like this where the store is created in order to replace the reducer with the hot loaded one

`if (module.hot) {
    module.hot.accept('../reducers/index', () => {
      const nextReducer = combineReducers(require('../reducers/index'));
      store.replaceReducer(nextReducer);
    });
  }`

**Comment by justin808** [comment]
@exciton So, close issue? Any PR or to-do from this info?

**Comment by justin808** [comment]
@exciton Please submit a PR and let's add this!

**Comment by exciton** [comment]
Had a few attempts to get this to work in the tutorial - but no luck yet. I have it working on my project so shouldn't be too much effort to find what the problem is.

**Comment by justin808** [comment]
If anybody solves this, please post here!

**Comment by bennyn** [comment]
Here is an example on how to integrate HMR for reducers: https://github.com/welovecoding/website/pull/62

It needs [react-hot-loader](https://www.npmjs.com/package/react-hot-loader).

**Comment by justin808** [comment]
We need to get the project updated for hot reloading. See #443.
