### ISSUE TITLE
Render form with errors ala Rails with react-router

### ISSUE THREAD

**Issue by hisapy** [shakacode/react-webpack-rails-tutorial#240]
I'm wondering how you guys do when submitting form with errors via normal HTTP POST using react-router to display components.

I have a routes.js file like the following 

```javascript
import React from 'react';
import { Router, Route } from 'react-router';

import ProductsIndex from 'products/Index';
import ProvidersIndex from 'providers/Index';
import PurchasesIndex from 'purchases/Index';
import ProviderForm from 'providers/Form';
import PurchaseForm from 'purchases/Form';

const wrapper = (Component, props) => {
  return React.createClass({
    render: () => {
      return React.createElement(Component, props);
    }
  })
}

class Index extends React.Component {
  render () {
    return this.props.children;
  }
}

const createRoutes = (browserHistory, props) => {
  return (
    <Router history={browserHistory}>
      <Route path="/admin/" component={Index}>
        <Route path="products" component={wrapper(ProductsIndex, props)} />

        <Route path="providers" component={wrapper(ProvidersIndex, props)} />
        <Route path="providers/new" component={wrapper(ProviderForm, props)} />
        <Route path="providers/:id/edit" component={wrapper(ProviderForm, props)} />

        <Route path="purchases" component={wrapper(PurchasesIndex, props)} />
        <Route path="purchases/new" component={wrapper(PurchaseForm, props)} />
        <Route path="purchases/:id/edit" component={wrapper(PurchaseForm, props)} />
      </Route>
    </Router>
  )
}

export default createRoutes;
```

My problem is that when I submit a form with errors, for example the PurchaseForm, to POST /admin/purchases/ (PurchasesController#create), the controller response is to render the form view again but since the route is /admin/purchases and react-router routes don't know about HTTP method used in the request, then the PurchasesIndex is rendered instead.
 
Currently, my solution will be to use an specific route to **create** and **update** actions but I'd like to know if I can have something more "elegant"

**Comment by seoyoochan** [comment]
No need to write all the routes of purchases, providers.
they seem like Backend API, which is Rails routes.
I dispatch actions with `redux` and `axios` package inside a component.
this way you can redirect a user or show just errors on the current page depending on the returned response from the action.

**Comment by alexfedoseev** [comment]
@hisapy why you don't want to submit form via xhr and handle response with errors in the handler?

**Comment by hisapy** [comment]
@alexfedoseev @seoyoochan 

Thx for your responses. 

Many of the forms in the app were originally .html.erb before becoming React components and because of _project deadlines_ we were trying to _avoid having to rewrite_ request/response/redirect stuff and reuse the "standard" form submission. 

As I mentioned before, my current solution (ie.: to update a Provider) is:

- Add explicit update route in Rails

```ruby
resources :providers, only: [:index, :show, :new, :edit, :destroy] do
  patch '/update', to: 'providers#update', on: :member, as: :update
  # other stuff here
end
```
- And then add the corresponding route in React

```jsx
<Route path="providers/:id/update" component={wrapper(ProviderForm, props)} />
```

I'll take a closer look at axios and other approaches in the next iteration of our project. 

Anyways, something I'm not sure about yet it what happens with redirects when using only XHR. Apparently they all get replaced with `window.location`, don't they?

**Comment by seoyoochan** [comment]
@hisapy in that case, maybe `getComponent`, `onEnter` , `onLeave` callbacks could be helpful.

[getComponent](https://github.com/reactjs/react-router/blob/master/docs/API.md#getcomponentlocation-callback)

**Comment by hisapy** [comment]
Thx @seoyoochan  ... I didn't know about those callbacks and indeed it seems they could be helpful

**Comment by justin808** [comment]
@hisapy Should we close this?

**Comment by hisapy** [comment]
I'd like to see some more responses to the question but It's up to you @justin808
