### ISSUE TITLE
HMR doesn't rerender components extended from BaseComponent

### ISSUE THREAD

**Issue by Igor10k** [shakacode/react-webpack-rails-tutorial#245]
I've used `foreman start -f Procfile.dev` to start the server, went to `localhost:3000`. Opened `Layout.jsx` and tried changing some text, but nothing happened in the browser even though I see in the terminal that webpack sends the `hot-update`. 
Then I tried replacing `extends BaseComponent` with `extends React.Component` which basically means I made `shouldComponentUpdate` always return `true`. After these changes modifying `Layout.jsx` was instantly reflected in the browser.
Something is definitely wrong since HMR should do `.forceUpdate()` for every changed component and rerender the component ignoring the `shouldComponentUpdate`.

**Comment by justin808** [comment]
@Igor10k Keep me posted on what you find out. If you figure out a good change, please submit a PR.

I've tested the hot reloading and changing the the JSX in the render method, and hot reloading works great.

**Comment by Igor10k** [comment]
@justin808 I made a 1-minute video showing the process and the difference when using `BaseComponent` and `React.Component` for `Layout.jsx`. I cloned the tutorial repo about 3 days ago, so it's quite fresh. I do a manual refresh in the video just once after I change `BaseComponent` to `React.Component` (and accidentally click the readme link :smiley: ).

https://dl.dropboxusercontent.com/u/2526191/react_on_rails_hmr.mov

Maybe you are doing some other changes that do trigger the hot reloading.

**Comment by justin808** [comment]
@Igor10k We're not doing anything in particular. This sounds like a bug in the hmr.

**Comment by Igor10k** [comment]
@justin808 so are you having the same behavior?

**Comment by Igor10k** [comment]
@justin808 https://github.com/gaearon/react-transform-boilerplate/issues/123

Fixed HMR by adding `"superClasses": ["React.Component", "BaseComponent"]` to the babel config.

**Comment by justin808** [comment]
:clap: Nice job @Igor10k. Any chance that you can throw that in a document PR here: https://github.com/shakacode/react_on_rails/tree/master/docs/additional_reading

We can call the file "hot-module-replacement.md".

Thanks!

**Comment by Igor10k** [comment]
I don't think that there's a need for another doc. How about just adding that `superClasses` line to the config and adding a comment above describing it. Something like "Enable rerendering of the components extended from BaseComponent" should be enough.

**Comment by justin808** [comment]
https://github.com/shakacode/react_on_rails/issues/332 discusses the issues.

**Comment by marz0** [comment]
I copied down the repo yesterday and I'm seeing the same issue. Changing the `BaseComponent` to `React.Component` fixed the problem. @Igor10k Are you saying that you added that line to your `.babelrc` file? I seem to get an error when I do that.

**Comment by Igor10k** [comment]
@marz0 
In this case the line should be added to `webpack.client.rails.hot.config.js` like

```js
{
  test: /\.jsx?$/,
  loader: 'babel',
  exclude: /node_modules/,
  query: {
    plugins: [
      [
        'react-transform', {
          superClasses: ['React.Component', 'BaseComponent', 'Component'],
          transforms: [
            {
              transform: 'react-transform-hmr',
              imports: ['react'],
              locals: ['module'],
            },
          ],
        },
      ],
    ],
  },
},
```

**Comment by Igor10k** [comment]
Btw, I decided to get rid of `BaseComponent` in favor of `pure-render-decorator` because there are also other things that depend on using the original class like `eslint-plugin-react` and I don't favor the idea of configuring every single plugin to work with `BaseComponent`.

**Comment by justin808** [comment]
@seoyoochan Maybe this contains the fix we need?

**Comment by seoyoochan** [comment]
@justin808 will check if this is the fix.

**Comment by justin808** [comment]
@seoyoochan Any update?

**Comment by seoyoochan** [comment]
@justin808 this was not related to my issue, stylesheet hrm rendering.

**Comment by LinuCC** [comment]
This really is a one-liner with the change to `webpack.client.rails.hot.config.js` @Igor10k proposed, or a bit more (plus another babel-plugin) with the decorator.

Which of those two would you prefer, @justin808?

**Comment by justin808** [comment]
I'm going to try out the one liner chante to the config.js file and merge that if it works for me.
