### ISSUE TITLE
Add Redux DevTools Extension to watch redux stores

### ISSUE THREAD

**Issue by seoyoochan** [shakacode/react-webpack-rails-tutorial#250]
Please add `Redux DevTools Extension` to watch redux stores.
[Redux DevTools Extension](https://github.com/zalmoxisus/redux-devtools-extension#redux-devtools-extension)
it makes debugging far easier.
you can revert/commit states of redux.

**Comment by alexfedoseev** [comment]
I suggest to use inline version of DevTools, extension's UX is poor when you use any of window managers.

**Comment by seoyoochan** [comment]
@alexfedoseev I've used both so far, inline version works well. but when including it in `Provider`, it needs a div additionally which breaks the design of app. When I work with my designer, he didn't like it because of that, so he had to manually remove it when he works on html/css markup.

**Comment by alexfedoseev** [comment]
@seoyoochan It's strange that pure div is causing such problem but I'm sure css reset or applying css class to this div will solve it.

**Comment by seoyoochan** [comment]
@alexfedoseev i will give you a short example from one of my client's project. Note that I didn't use the react_on_rails gem. 

The below code wraps all the components with the pure div.
as you mentioned, i guess applying class to the div can be a workaround.

```
var routes = (
  <Provider store={store}>
    <div>
    <Router history={browserHistory}>
      <Route path='/' component={App}>
        <Route
          path="login"
          component={Login}
        />
        <Route
          path="links/:link_token"
          component={ModalDocGuest}
        />
        <Route component={Authenticated}>
          <Route component={Dashboard}>
            <IndexRoute
              components={{
                main: MainServices,
                aside: Aside
              }}
              />
              <Route
                path="recent"
                components={{
                  main: MainRecent,
                  aside: Aside
                }} />
              <Route
                path="favorite"
                components={{
                  main: MainFavorite,
                  aside: Aside
                }} />
              <Route
                path="links"
                components={{
                  main: MainLinks,
                  aside: Aside
                }} />
          </Route>
        </Route>
      </Route>
    </Router>
    <DevTools />
    </div>
  </Provider>
);

ReactDOM.render(
  routes,
  document.getElementById('app')
);
```

**Comment by justin808** [comment]
@seoyoochan @alexfedoseev Maybe we can have a couple PRs to compare?

**Comment by alexfedoseev** [comment]
I guess PR won't show the difference: extension implementation is easier, but its UX is pure. I can't use it with my window manager and I forced to click on the icon to see the log (just no). When it's implemented inline, it's inside the window and you can bind hot keys to control it.

**Comment by seoyoochan** [comment]
Yeah the hot keys are a way to control the window. We can add the inline version then. :)

**Comment by justin808** [comment]
@seoyoochan I was thinking about this today. Do you have a PR? I might take care of this soon, but if you can, that would be great.

**Comment by seoyoochan** [comment]
@justin808 It is not trivial to do a PR, but I want you to decide whether we want to use either `inline version` or `extension version`.

**Comment by justin808** [comment]
@alexfedoseev I'll go with your preference.

**Comment by justin808** [comment]
@seoyoochan I took a look at using the "inline" way recommended by @alexfedoseev and that looks really good.

**Comment by crysislinux** [comment]
You can install the extension to enable the extension version or fallback to the inline version.

> window.devToolsExtension ? window.devToolsExtension() : DevTools.instrument()

**Comment by justin808** [comment]
@alexfedoseev Let's get your recommendation meged. What do you say?
