### ISSUE TITLE
Hot Reloading Not Working

### ISSUE THREAD

**Issue by atwoodjw** [shakacode/react-webpack-rails-tutorial#251]
If I follow the steps in Basic Setup and run `foreman start -f Procfile.hot`, I'm not seeing changes hot-loaded; I have to refresh the page.

![recordit](http://g.recordit.co/N0M274Xbkc.gif)

**Comment by justin808** [comment]
See: https://github.com/shakacode/react_on_rails/issues/332

We might need to update some npm libraries.

**Comment by justin808** [comment]
And see #245

**Comment by justin808** [comment]
@seoyoochan and I saw this. Might have something to do with the package versions.

**Comment by justin808** [comment]
Please move the discussion to #245.
