### ISSUE TITLE
Will this get in the way of jQuery Mobile?

### ISSUE THREAD

**Issue by dt1973** [shakacode/react-webpack-rails-tutorial#265]
Sorry but I'm new to this. My Rails app uses jQuery Mobile for a lot of stuff. Would this tutorial enhance that or replace it?

**Comment by justin808** [comment]
This question is sort of N/A. React uses a totally different conceptual model of a virtual DOM, while jQuery heavily relies on DOM manipulation.

That being said, you can use the techniques here to gradually add new screens based on React. React is *FAR SUPERIOR* to using jquery-mobile, IMHO.

You can find jquery-mobile on npm: https://www.npmjs.com/package/jquery-mobile

**Comment by dt1973** [comment]
Thank you for the clarification. Have a good one!

**Comment by dt1973** [comment]
But basically it's either or? If I were to switch to React, I'd have to replace all my 50+ jQuery-based libraries?

**Comment by justin808** [comment]
You are free to use both of them, but now within the same screen area. It's common for apps to migrate gradually.
