### ISSUE TITLE
Please update somethings...

### ISSUE THREAD

**Issue by riseshia** [shakacode/react-webpack-rails-tutorial#272]
Hi, I'm shia and I just trying to follow this turorial, and found somethings.
Here it is,
 - need to add `gem "listen"` to `Gemfile`. If not, user can't run server. [link](https://github.com/rails/rails/issues/24063)
 - Default server port is not correct. it's not 3000, but 5000. Maybe only my case, but it seems not to be. Here is my environments:
```
ruby 2.3.0-p0
rails 5.0.0.beta3
el capitan 10.11.4
```

And logs, maybe not helpful ;(
```
| > babel-node server-rails-hot.js
| 
| Webpack dev build for Rails
| => 🔥  Webpack development server is running on port 3500
| => Booting Puma
| => Rails 5.0.0.beta3 application starting in development on http://0.0.0.0:5000
| => Run `rails server -h` for more startup options
| => Ctrl-C to shutdown server
| [8591] Puma starting in cluster mode...
| [8591] * Version 3.4.0 (ruby 2.3.0-p0), codename: Owl Bowl Brawl
| [8591] * Min threads: 5, max threads: 5
| [8591] * Environment: development
| [8591] * Process workers: 2
| [8591] * Preloading application
| [8591] * Listening on tcp://0.0.0.0:5000
| [8591] Use Ctrl-C to stop
| [8591] - Worker 0 (pid: 8615) booted, phase: 0
| [8591] - Worker 1 (pid: 8616) booted, phase: 0
```

Thanks to your working on this!

**Comment by justin808** [comment]
@riseshia Please confirm these are now addressed (listen definitely is in the gemfile) and puma runs on port 3000: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/config%2Fpuma.rb#L12

**Comment by riseshia** [comment]
sorry, I checked late.
checked 'listen' gem in Gemfile and configuration of puma.
I will notice if I'll make another try and fail to open port 3000.
Thanks for your answer :)
