### ISSUE TITLE
Missing right parenthesis in package.json

### ISSUE THREAD

**Issue by shunwen** [shakacode/react-webpack-rails-tutorial#279]
https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/package.json#L18

    "build:client": "(cd client && npm run build:client --silent",

**Comment by justin808** [comment]
@shunwen Please submit a PR if you like. Or let me know and I'll fix it.

**Comment by shunwen** [comment]
Created PR #280 . Thanks.
