### ISSUE TITLE
Get state in checkAuth

### ISSUE THREAD

**Issue by vmpj** [shakacode/react-webpack-rails-tutorial#289]
Currently in `TestReactRouterRedirect` a redirect is demonstrated and the state is stubbed. 

```
export default class TestReactRouterRedirect extends BaseComponent {
  static checkAuth(nextState, replace) {
    // Hard code this to demonstrate the effect
    const notAuthorized = true;
    if (notAuthorized) {
      replace({ pathname: '/', state: { redirectFrom: nextState.location.pathname } });
    }
  }
```
What would be the react-on-rails way to access/get state at this point? I've tried a few approaches with no success. Thanks.

**Comment by justin808** [comment]
Hi @vmpj. What sort of state are you looking for?

**Comment by vmpj** [comment]
Hey @justin808, say I have a bool `isLoggedIn` stored in some redux store. I'm not exactly sure how to access it. 

The solution I got working was based on [an implementation](https://github.com/joshgeller/react-redux-jwt-auth-example) using a higher-order component to wrap protected views.

**Comment by justin808** [comment]
@vmpj Did you solve your problem? You will want to see these for inspiration:

* https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/app/bundles/comments/startup/ClientRouterApp.jsx

* https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/app/bundles/comments/startup/ClientRouterApp.jsx

We use redux to store application state.

**Comment by vmpj** [comment]
Thanks @justin808. I'll check it out.
