### ISSUE TITLE
Demo App Server Error

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#295]
From @Undistraction
With the demo app here: [http://www.reactrails.com/?](http://www.reactrails.com/? ) the following message is displayed if a name is entered but no text is entered:

> Your comment was not saved! A server error prevented your comment from being saved. Please try again.

If a value for text is required, this should be indicated and a more appropriate error message should be displayed as it initially appears the app is broken.

-----

I agree.

@undistraction, want to submit a PR?

**Comment by justin808** [comment]
@dzirtusss Take a look at this one.

**Comment by justin808** [comment]
We're not getting the error text: `          error={data.get('submitCommentError')}`

from `client/app/bundles/comments/components/CommentBox/CommentBox.jsx`

```js
    return (
      <div className="commentBox container">
        <h2>
          Comments {data.get('isFetching') && 'Loading...'}
        </h2>
        <p>
          <b>Text</b> supports Github Flavored Markdown.
          Comments older than 24 hours are deleted.<br />
          <b>Name</b> is preserved. <b>Text</b> is reset, between submits.
        </p>
        <CommentForm
          isSaving={data.get('isSaving')}
          error={data.get('submitCommentError')}
          actions={actions}
          cssTransitionGroupClassNames={cssTransitionGroupClassNames}
        />
        <CommentList
          $$comments={data.get('$$comments')}
          error={data.get('fetchCommentError')}
          cssTransitionGroupClassNames={cssTransitionGroupClassNames}
        />
      </div>
    );
```

![2016-08-11_23-01-27](https://cloud.githubusercontent.com/assets/1118459/17617767/97365ece-6017-11e6-9bde-930c20a1d22e.png)

![2016-08-11_23-02-21](https://cloud.githubusercontent.com/assets/1118459/17617789/b99d1fc0-6017-11e6-9c18-ff311e372136.png)

**Comment by dzirtusss** [comment]
Its also not showing error when 1) name is blank 2) on React Router page

**Comment by justin808** [comment]
@AlexKVal has this one.
