### ISSUE TITLE
Broken link in readme file

### ISSUE THREAD

**Issue by milushov** [shakacode/react-webpack-rails-tutorial#297]
https://github.com/shakacode/react-webpack-rails-tutorial#js-and-css-assets

Link to `assets.rake` is broken.

**Comment by justin808** [comment]
@milushov Can you submit a PR? Thanks!

**Comment by milushov** [comment]
yes, but I don't know what it should be :(

**Comment by justin808** [comment]
@milushov It's no longer needed. I updated the docs.

**Comment by milushov** [comment]
ok, thanks
