### ISSUE TITLE
Application not working with express server

### ISSUE THREAD

**Issue by milushov** [shakacode/react-webpack-rails-tutorial#299]
When application running with express server: `foreman start -f Procfile.express` (after this [fix](https://github.com/shakacode/react-webpack-rails-tutorial/pull/298/files)) I see the error -- 
![image](https://cloud.githubusercontent.com/assets/424326/16566243/796c67fe-421b-11e6-9365-7cc7946f535b.png)

Also, I have noticed that exactly on third call of the `commentsReducer` comments get `undefined` value and I don't have idea why..

![image](https://cloud.githubusercontent.com/assets/424326/16566166/2b56963e-421b-11e6-8733-9a481b4e426b.png)

**Comment by justin808** [comment]
Relates to #298.

We'll try to get this addressed ASAP.

**Comment by justin808** [comment]
@milushov The best way to debug this might be to put some print statements in the https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/server-express.js file.

**Comment by justin808** [comment]
It's fixed here: #313.

However, we need to decide if we should even keep this around. Maybe we should just strip using the express server completely?

@robwise @geoffevason @jbhatab @alexfedoseev Opinions?

**Comment by jbhatab** [comment]
@justin808 pretty sure we stripped this already.

**Comment by justin808** [comment]
@jbhatab I'm not talking about the new app generator. I'm talking about this repo.

**Comment by jbhatab** [comment]
@justin808 I keep getting faked out by that. Yeah that'd probably be a good idea.

**Comment by justin808** [comment]
Fixed in #313.
