### ISSUE TITLE
Change deployment to reactrails.com to use SSL

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#300]
We're building a react-native client (see https://github.com/shakacode/react-native-tutorial). In order to have an app on the app store, we'll need the API endpoint to point to a SSL source.

What are the options here?

CC: @dylangrafmyre

**Comment by justin808** [comment]
@dylangrafmyre Any easy (and free) way to tackle this one? Our react-native client is operational.

**Comment by dylangrafmyre** [comment]
What are you using for the backend API?

**Comment by dylangrafmyre** [comment]
If you are using the backend on Heroku, they have free SSL now:
https://devcenter.heroku.com/articles/ssl-endpoint

**Comment by zph** [comment]
@justin808 Chiming in here to offer some options depending on your deployment setup:

1) If you're on a bare VPS running Ubuntu: check out LetsEncrypt's SDK. Free, legit, and autorenewed each 90 days.
2) If you're on Heroku, follow @dylangrafmyre 's lead or you can still use LetsEncrypt (https://github.com/substrakt/letsencrypt-heroku)
3) If on AWS and behind cloudfront, you can get a free cert via their AWS Certificate Manager
4) If none of those free options work, I've happily used sslmate.com. Allows you to have mostly painless ssl experience.

Just in case this info helps :)
