### ISSUE TITLE
lost git commit sha

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#305]
https://github.com/shakacode/react-webpack-rails-tutorial/blob/66a9da7981564ba71b3556a9e13077712541b6cf/app/views/pages/_header.html.erb#L4

no longer works because I switched to the new heroku buildpacks system

Full details here: 

https://github.com/sreid/heroku-buildpack-sourceversion/issues/3

The link goes to the last commit on master which is not right if the deploy on master failed or if we deployed another branch.

![2016-07-11_16-36-52](https://cloud.githubusercontent.com/assets/1118459/16753441/b83edc36-4785-11e6-91b2-b91502d172fc.png)

**Comment by aaronvb** [comment]
@justin808 I did some digging around and found that the [detect script](https://github.com/sreid/heroku-buildpack-sourceversion/blob/master/bin/detect) in the above buildpack is not correct. It needs to print to stdout. 

`If the exit code is 0, the script must print a human-readable framework name to stdout` from https://devcenter.heroku.com/articles/buildpack-api#bin-detect

I found an updated version of the repo here: https://github.com/tempoautomation/heroku-buildpack-sourceversion

So replace your current build pack with `heroku buildpacks:set --index 3 https://github.com/tempoautomation/heroku-buildpack-sourceversion.git`

I've got it working here: https://avb-test-react-webpack.herokuapp.com/

**Comment by justin808** [comment]
OMG! Big thanks @aaronvb!

**Comment by aaronvb** [comment]
@justin808 no problem!
