### ISSUE TITLE
Convert from redux-thunk to redux-saga

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#314]
I'm looking for opinions here.

At team [ShakaCode](http://www.shakacode.com), we're using [redux-saga](http://yelouafi.github.io/redux-saga/) rather than [redux-thunk](https://github.com/gaearon/redux-thunk) for new projects.
## Options:
1. Move existing code to redux-saga, and keep a non-router version of the code using redux-thunk. Basically, one more tab.
2. Switch all the code to redux-saga.
## References:
- http://survivejs.com/blog/redux-saga-interview/
- https://shift.infinite.red/using-redux-saga-to-simplify-your-growing-react-native-codebase-2b8036f650de#.jv5y7sgs1
- http://stackoverflow.com/a/34933395/1009332

**Comment by justin808** [comment]
Check out this tutorial I made: https://forum.shakacode.com/t/experimenting-with-generators/657

**Comment by justin808** [comment]
As of right now, Thunk is easier to understand and debug.  See #315. We should probably make a new project with thunk.

That being said, it's a great exercise to convert the 2 simple async calls to thunk in a PR.

**Comment by dzirtusss** [comment]
I'll look at this issue

**Comment by justin808** [comment]
See #325

**Comment by yangmillstheory** [comment]
Just curious, do you all find the conceptual overhead of **redux-saga** worth it?

I've used Thunks extensively in a production application, and have had no issues or complaints.

In terms of testability, it still seems like you have to [manipulate generator internals](https://github.com/yelouafi/redux-saga/blob/master/examples/counter/test/sagas.js), which seems like a leaky abstraction.

With Thunks, it seems like it would be possible to [mock out XHR via Jest](https://facebook.github.io/jest/docs/getting-started.html#mocking-and-sandboxing) which would seem more straightforward.

I've also heard from less experienced members on my team that sagas were tough to debug and not as straightforward to use as Thunks.

***

Again, I don't have direct experience with sagas, just looking for an opinion from someone that's used both.

**Comment by justin808** [comment]
@yangmillstheory You should be able to mock either the saga or thunk with jest. In terms of debugging, yes, the chrome debugger is not good inside of the generator function. You have to use print statements. I think they are both good ways.

**Comment by justin808** [comment]
This one should have gotten merged. Any takers that want to create an updated PR with this?
