### ISSUE TITLE
Add flow annotations

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#315]
We're using [flow](https://flowtype.org/) on new projects at team [ShakaCode](http://www.shakacode.com). We should update this sample.

**Comment by justin808** [comment]
This might make the JS in this project too hard to read. We might want a new project:

react-on-rails-starter-kit, and that has all the advanced setup, including authentication, and a react-native client as well.

**Comment by JG0328** [comment]
Hello, I would like to take this Issue for my Application process.

**Comment by justin808** [comment]
@JG0328 this is really old. Ping me in Slack and let's find something more relevant. You can find the [slack link here](https://www.shakacode.com/open-source-projects).
