### ISSUE TITLE
Lodash FP vs. Lodash

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#322]
The ShakaCode team is using Lodash/FP on all new projects.

Should we convert this tutorial to use lodash/fp?

Arguments for and against?

**Comment by justin808** [comment]
@robwise would this example project be better with FP? It might not matter either way.

**Comment by robwise** [comment]
@justin808 I think we're only using it in like 4 places, and 3 of them are `bindAll`, so we might as well convert it over?

**Comment by p4sh4** [comment]
An "against" argument coming from someone who is new to the modern JS ecosystem:

**Comment by p4sh4** [comment]
An "against" argument - this project already has a somewhat significant mental overhead for someone who is new to the modern JS ecosystem, and I believe that this kind of developer would be most attracted to `react_on_rails`. Most people are familiar with Lodash. But seeing "Lodash/FP" would require some reading of articles/docs to understand the differences and advantages (and if you're new to functional programming, you're in for a ride!). 

Maybe separating the project into a "starter kit" and an "advanced kit" as discussed in some other issues might be a way to go. I'm just afraid that many things aren't trivial to understand for someone coming from Rails (postcss modules, Webpack etc.), and making it even harder might scare people away from using the project.

**Comment by justin808** [comment]
@p4sh4, @robwise We have a few options.

1. Separate repos.
2. Separate sub-directories with different examples in same repo.

What I like about one repo is that:

1. Can use the same Rails back end.
2. Can be published to reactrails.com

Some of the things will be "global":

1. The webpack config with hot reloading, CSS modules
2. Rails API

What will vary:

1. React-Native Client
2. Simple examples, possibly with no redux
3. More advanced examples with react-router, redux-saga, lodash/fp, etc.

Thoughts?

**Comment by robwise** [comment]
Is option 2 the way it is now? I definitely don't like 1 because that would hurt maintainability.

**Comment by justin808** [comment]
We'll stick with Lodash plain for now. Lodash/FP is going into [react-on-rails-pro](https://forum.shakacode.com/t/introducing-react-on-rails-pro-subscriptions/785).
