### ISSUE TITLE
Demonstrate this in a docker container

### ISSUE THREAD

**Issue by EDeijl** [shakacode/react-webpack-rails-tutorial#331]
It would be great if this project has a Dockerfile
It is a pretty complete application that a lot of people could learn from

**Comment by sub2u** [comment]
I will push the Dockerfile for this project soon.

**Comment by sub2u** [comment]
Created the pull request https://github.com/shakacode/react-webpack-rails-tutorial/pull/332

**Comment by justin808** [comment]
This one almost made it to the finish line. It does need updating. Any takers?

**Comment by thetonyrom** [comment]
I'll handle it.

**Comment by thetonyrom** [comment]
Hi @justin808 . I've just submitted an initial dockerized version, have a look.

**Comment by Trip4077** [comment]
If this still needs work, I will be happy to look at it as a part of my application process.

**Comment by justin808** [comment]
See #507
