### ISSUE TITLE
Update to Webpack v2 and Yarn

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#336]

**Comment by cubadomingo** [comment]
Any updates on how this is going? I'd like to possibly give it a try.

**Comment by justin808** [comment]
https://blog.shakacode.com/migration-to-webpack-2-c9803871b931#.8wdrh4ivv

**Comment by justin808** [comment]
@richa is doing this one.

**Comment by justin808** [comment]
@cubadomingo You're welcome to give this a try.

We're building a subscription "React on Rails Pro" which will include updated examples, such as using yarn and Webpack v2. If you're interested in such a service of great examples of using React on Rails and priority support from the ShakaCode team, please get in touch with me directly at justin@shakacode.com.

**Comment by justin808** [comment]
@squadette would you be interested in tackling this one?

@cubadomingo did you still want to do this one?

**Comment by justin808** [comment]
@squadette? @cubadomingo? still interested?

**Comment by justin808** [comment]
We should do the react-router v4 migration separately.

@matk0 is going to take this on.

**Comment by cubadomingo** [comment]
@justin808 sorry for the late response. I've been on vacation and head back in about a week. I'd be more than happy to tackle this.

**Comment by matk0** [comment]
@cubadomingo feel free to take this up. I have not started yet.

**Comment by justin808** [comment]
@cubadomingo That would be great. I'll put a label on this issue. To prevent blocking others, I'll give you a few days to see some progress before assigning to another. Please see the /spec/dummy directory of https://github.com/shakacode/react_on_rails for an example of the changes. See recent PRs there: https://github.com/shakacode/react_on_rails/pull/752

**Comment by justin808** [comment]
@cubadomingo Any word on this one?

**Comment by justin808** [comment]
Since I haven't heard from @cubadomingo, this one is now up for grabs.

Some ideas here:
* https://github.com/shakacode/react-webpack-rails-tutorial/issues/361#issuecomment-288011764
* https://github.com/retroalgic/react-on-rails-hot-minimal
 
And /spec/dummy from the main https://github.com/shakacode/react_on_rails.

**Comment by kaizencodes** [comment]
I'll take this if no one has started it.

**Comment by justin808** [comment]
@kaizencodes You got it!
