### ISSUE TITLE
Small change to readme

### ISSUE THREAD

**Issue by chrislerum** [shakacode/react-webpack-rails-tutorial#339]
Under 'Basic Demo Setup', step 11 says go to localhost:3000, but when I set this up from scratch just now, it started the rails app at localhost:5000.

**Comment by justin808** [comment]
The puma.rb file says: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/config/puma.rb#L12

Port 3000.

I think you have something overriding it.
