### ISSUE TITLE
Is Redis missing from Foreman Procfile?

### ISSUE THREAD

**Issue by creativetags** [shakacode/react-webpack-rails-tutorial#358]
I'm just trying to get the tutorial to run on my machine to play with it. I did foreman start -f Procfile.hot then loaded http://localhost:5000/ and posted a comment. Then I saw this:

Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
16:48:13 rails.1               | /Users/mark/.rvm/gems/ruby-2.4.0@test-react-on-rails/gems/redis-3.3.3/lib/redis/client.rb:345:in `rescue in establish_connection': Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)

I'm guessing action_cable needs Redis and it wasn't started?

**Comment by creativetags** [comment]
For anyone else following along you can bypass this issue in development by changing from Redis to async in config/cable.yml

```
development:
  adapter: async
```

**Comment by reconstructions** [comment]
Or you can just add the following to the bottom of your Procfiles: `redis: redis-server --port 6379`
