### ISSUE TITLE
Possible to use React Hot Loader?

### ISSUE THREAD

**Issue by mattfordham** [shakacode/react-webpack-rails-tutorial#361]
Hi there!

Desipte the link in the [React on Rails Doctrine](https://blog.shakacode.com/the-react-on-rails-doctrine-3c59a778c724#.q8pcumtie) to [React Hot Loader](https://github.com/gaearon/react-hot-loader), it seems this project is using the deprecated [React Transform HMR](https://github.com/gaearon/react-transform-hmr) project.

Has anyone had success implementing React Hot Loader yet and/or have an example of implementation? Specifically, I am getting hung up on where/how to use the `module.hot.accept` stuff.

Thanks!

**Comment by mattfordham** [comment]
FWIW, I think I figured it out a good way to do this...

```
import React from 'react';
import ReactOnRails from 'react-on-rails';
import { AppContainer } from 'react-hot-loader';

import HelloWorld from './HelloWorld';

const App = (props, _railsContext) => {
  if (module.hot) {
    module.hot.accept('./HelloWorld', () => {
      ReactOnRails.reactOnRailsPageLoaded();
    });
  }

  return (
    <AppContainer>
      <HelloWorld {...props} />
    </AppContainer>
  );
};

ReactOnRails.register({ App });
```

This seems to work, although I havn't tested thoroughly.

**Comment by justin808** [comment]
@mattfordham Can you help me with a PR with these updates? I'd be glad to give you help!

**Comment by mattfordham** [comment]
Yeah, I'd love to try! Won't me immediately, but will put on the list ;)

**Comment by justin808** [comment]
This is related: https://github.com/shakacode/react_on_rails/pull/742

**Comment by Judahmeek** [comment]
Also https://github.com/shakacode/react_on_rails/issues/332. I've been exploring this problem domain and I don't think `ReactOnRails.reactOnRailsPageLoaded()` is the best choice since it rerenders all registered components regardless of the scope of the hot update.

**Comment by justin808** [comment]
@Judahmeek @mattfordham FWIW, the hot loader seems to work GREAT if you are not using CSS modules.

**Comment by Judahmeek** [comment]
@justin, what about flexbox?

**Comment by retroalgic** [comment]
@mattfordham 
`React Hot Loader` works great with React on Rails. But you shouldn't use `ReactOnRails.reactOnRailsPageLoaded()` as at least it won't work with `Redux` out of the box. You just need something like `ReactDOM.render(element, document.getElementById(domNodeId))` in your root component. You can check out my [minimal demo here](https://github.com/retroalgic/react-on-rails-hot-minimal) for more details.

@justin808 I don't have any issue with `React Hot Loader` when using `CSS modules` or even `react-css-modules`. It works perfect.

**Comment by justin808** [comment]
We need to update this repo for the current version of hot reloading.

Take a look at this issue: https://github.com/shakacode/react_on_rails/issues/772

**Comment by justin808** [comment]
See https://github.com/shakacode/react_on_rails/pull/865 for an example of what needs to be done! Any volunteers for this?

**Comment by justin808** [comment]
Take a look at #443. Any volunteers?
