### ISSUE TITLE
When I run 'cd client && npm run build:dev:client' it hangs forever

### ISSUE THREAD

**Issue by admazzola** [shakacode/react-webpack-rails-tutorial#362]
I implemented this into my own project but now when I use Procfile.static or just run 'cd client && npm run build:dev:client' manually, this is the output: 

`> webpack -w --config webpack.client.rails.build.config.js

Webpack dev build for Rails
Hash: 7226237f324ed5b56978
Version: webpack 1.14.0
Time: 5968ms
                                 Asset     Size  Chunks             Chunk Names
  f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]  
448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]  
 fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]  
  e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]  
  89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]  
                         app-bundle.js  3.04 MB       0  [emitted]  app
                      vendor-bundle.js  7.78 MB       1  [emitted]  vendor
                     vendor-bundle.css   148 kB       1  [emitted]  vendor
   [0] multi app 52 bytes {0} [built]
   [0] multi vendor 256 bytes {1} [built]
    + 1269 hidden modules
Child extract-text-webpack-plugin:
                                     Asset     Size  Chunks             Chunk Names
      f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]  
    448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]  
     fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]  
      e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]  
      89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]  
        + 7 hidden modules
`

And the terminal hangs and never completes that process.  There is no error, using Procfile.static.trace doesnt help, and therefore I have no idea how to fix the issue.  My Procfile.hot works fine and I can even deploy (albeit I have a separate issue with bootstrap being loaded twice in that instance that I cant solve either...)  What do I do ??

**Comment by Judahmeek** [comment]
A google search of "webpack hanging" suggests issues with `sass-loader` and `node-sass`. Also, try using some of the [Webpack CLI options](https://webpack.github.io/docs/cli.html) to identify which chunk is causing your issues.

**Comment by justin808** [comment]
Closing for now.
