### ISSUE TITLE
React-router not included in client/package.json

### ISSUE THREAD

**Issue by mnd-dsgn** [shakacode/react-webpack-rails-tutorial#363]
When I follow the [basic tutorial](https://github.com/shakacode/react_on_rails/blob/master/docs/tutorial.md) for setup, then try to use something imported from 'react-router' in a component, it throws an error:

```
ERROR in ./app/bundles/HelloWorld/components/Main.jsx
Module not found: Error: Can't resolve 'react-router' in /Users/matthewhinea/Programming/javascript/react/trello-react/client/app/bundles/HelloWorld/components'
```

Looking in `client/package.json`, I see that it's because some dependencies that you have in the [example tutorial file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/package.json) are missing, namely:

```
    "react-router": "^3.0.0",
    "react-router-redux": "^4.0.7",
```

Adding these to `client/package.json` and running `npm install` from the `client` directory fixes it.

Should it be already included, or is running `cd client && npm install react-router --save` actually necessary before using react-router?

Thanks!

**Comment by justin808** [comment]
@mnd-dsgn You need to add **ALL** packages that you need, and you should use `yarn add` or `npm i --save`.
