### ISSUE TITLE
Tests are insufficient for JS code

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#37]
See below image.

If you make an intentional typo, I'd like to see some JS tests pass.

Incidentally, this is caught nicely by the rspec tests.

![hello_react](https://cloud.githubusercontent.com/assets/1118459/7754529/0a59835e-ff89-11e4-8822-db43acb5cd44.jpg)

![3__default__justin_justinmbp-2___rvm_project_path__zsh_](https://cloud.githubusercontent.com/assets/1118459/7754596/96a6b746-ff89-11e4-88f2-ebcaa8ce94a6.jpg)

**Comment by justin808** [comment]
We'll probably use this as an example:

https://github.com/gaearon/redux/tree/breaking-changes-1.0/examples/todomvc/test

CC: @alexfedoseev

**Comment by alexfedoseev** [comment]
I'm setting up test env for redux at the moment, will take a look at this right after.

**Comment by justin808** [comment]
This was fixed a while ago: https://github.com/shakacode/react-webpack-rails-tutorial/tree/master/client/test
