### ISSUE TITLE
No such file or directory @ rb_file_s_mtime - app/assets/webpack/server-bundle.js

### ISSUE THREAD

**Issue by ceres629** [shakacode/react-webpack-rails-tutorial#371]
No such file or directory @ rb_file_s_mtime - app/assets/webpack/server-bundle.js

After installing the latest version of the project and following the readme instructions I get the above error when I run the server and visit the root url.

It occurs here: 
<%= react_component('RouterApp', id: "RouterApp-react-component-0") %>

**Comment by justin808** [comment]
Did you start the project using `foreman start -f Procfile.dev` ?

**Comment by cehsu** [comment]
What port does it indicate in the message `Rails 5.0.2 application starting in development on http://0.0.0.0:XXXX` when you run `foreman start -f Procfile.hot`. Is it something besides 3000? If so, perhaps try navigating to localhost:XXXX. (This resolved a similar issue for me.)

**Comment by justin808** [comment]
I use this in my `.zshrc`

`export PORT=3000`

Forman uses that.

**Comment by ceres629** [comment]
The problem was solved by indeed using `foreman start -f Procfile.dev`
