### ISSUE TITLE
Uncaught Error: Cannot find module "libs/i18n/translations"

### ISSUE THREAD

**Issue by ceres629** [shakacode/react-webpack-rails-tutorial#372]
It is looking for a file libs/i18n/translations.js but no such file exists in the repo where does this file come from?

**Comment by probepark** [comment]
I have occured same issue.

**Comment by justin808** [comment]
This is built by the rake task.

See https://github.com/shakacode/react_on_rails/blob/master/docs/basics/i18n.md

**Comment by justin808** [comment]
See https://github.com/shakacode/react-webpack-rails-tutorial/pull/377

**Comment by saroar** [comment]
this is not wokring for me too http://prntscr.com/foccb7
  # Replace the following line to the location where you keep translation.js & default.js for use
  # by the npm packages react-intl. Be sure this directory exists!
  config.i18n_dir = Rails.root.join("client", "app", "libs", "i18n")

**Comment by hakongit** [comment]
I'm having a similar problem - running 

`bundle exec rake react_on_rails:locale`

does not generate any files, no (error) message of any kind.
