### ISSUE TITLE
Errors with switching tabs

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#381]
Obscure error:
https://facebook.github.io/react/docs/error-decoder.html?invariant=32&args[]=23

```
Unable to find element with ID 23.
```

Reproduction:

1. Start app
2. Click on "Simple React" tab (or Classic Rails)
3. Click back on "React Router Demo" tab (or React Demo tab).
4. See error in console.

![2017-04-04_23-13-29](https://cloud.githubusercontent.com/assets/1118459/24698651/27046f62-198d-11e7-9767-fabb6ab2eb90.png)

**Comment by justin808** [comment]
@richa Mentioned to me on Slack:

here is the culprit: https://github.com/richa/react-webpack-rails-tutorial/commit/ac9af685609047ebed461d10a2280cb35eff00d9
GitHub
removed stale App.cable code in CommentBox · richa/react-webpack-rails-tutorial@ac9af68
react-webpack-rails-tutorial - Example of integration of Rails, react, redux, using the react_on_rails gem, webpack, enabling the es7 and jsx transpilers, and node integration. And React Native! Live Demo:

Fix: 
Need to remove this stale componentWillUnmount code last time

**Comment by naldokan** [comment]
I'm Oscar Endo. I'm grabbing this issue!

**Comment by naldokan** [comment]
I've a question.
In my local environment, I can't find this error. I pulled from master branch.
Could you tell me the reason?
