### ISSUE TITLE
Upgrade JS and Ruby Libraries

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#382]
I'd like to get all the JS and Ruby libraries updated.

Anybody want to help?

**Comment by tmobaird** [comment]
@justin808 I can help out! Do you just want to update the gem/node module versions? or the ruby and node versions as well?

**Comment by justin808** [comment]
Let's update all. Thanks @tmobaird!

**Comment by tmobaird** [comment]
@justin808 did you want to jump to the most recent, stable versions for node (7.8.0) and ruby (2.4.1)?

**Comment by justin808** [comment]
> @justin808 did you want to jump to the most recent, stable versions for node (7.8.0) and ruby (2.4.1)?

YES!

**Comment by justin808** [comment]
Halfway done! #383!

**Comment by tmobaird** [comment]
Currently waiting on the next release of react-bootstrap that is compatible with react v >= 15.5.0.

**Comment by tmobaird** [comment]
Ok, It looks like react-bootstrap has finally updated everything for react v15.5. I will continue upgrading these dependencies tomorrow!

**Comment by justin808** [comment]
@tmobaird FABULOUS!

**Comment by tmobaird** [comment]
@justin808 sorry for the false alarm. It looks like react-bootstrap has a couple dependencies (react-overlays and uncontrollable) that have not been updated yet and are still using deprecated react syntax. Lets wait a couple more days on this

**Comment by justin808** [comment]
@tmobaird want to try again? BTW: https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b 

Let's bump Webpack as well!

**Comment by tmobaird** [comment]
@justin808 definitely! I'll knock this out asap! 👍

**Comment by justin808** [comment]
@tmobaird Any progress?

**Comment by tmobaird** [comment]
@justin808 actually yes! Sorry this has taken so long, but react router v4 is fundamentally different from the earlier versions so it required some extra work to update the router code for both client and server side.

I should have a PR up by today or tomorrow with updates for a lot of the main JS dependencies.

**Comment by justin808** [comment]
@tmobaird, check out #443. We're also in the process of hiring right now, if you know anybody looking. Anybody interested can [email me](mailto:justin@shakacode.com).
