### ISSUE TITLE
File uploads with React on Rails

### ISSUE THREAD

**Issue by dineshPallapa** [shakacode/react-webpack-rails-tutorial#384]
If someone adds File upload functionality with react on rails using gems like paperclip or carrier wave to this tutorail hope It helps a lot for beginners.

**Comment by justin808** [comment]
@dineshPallapa I think that's out of the scope of this project. That being said, we're doing that sort of thing for [React on Rails Pro](https://forum.shakacode.com/t/introducing-react-on-rails-pro-subscriptions/785). Message me back if that interests you.
