### ISSUE TITLE
Hot Assets Server CORS 'Access-Control-Allow-Origin' Error with Webpack 2

### ISSUE THREAD

**Issue by reconstructions** [shakacode/react-webpack-rails-tutorial#393]
Sorry in advance for asking for help with a problem in my own app instead of this repo...

I merged everything since ef369ed9d922aea5116ca7e50208169fd7831389 into an app I had build on top of that commit (mostly Webpack 2 and version bumps), and it broke my hot reloading:

![commit_fail](https://cloud.githubusercontent.com/assets/5771932/26435672/be8ddd3c-40c5-11e7-96b8-fd9e05c5d23e.jpg)

My own app has some differences (Foreman ports are set in a `development.env` file, Bootstrap styles have been removed), but I have gone through and merged all the commits after the one I started from about 5 times and I cannot figure out how it breaks hot reloading.  

Any advice would be greatly appreciated, otherwise I will have to try to start again from the latest commit and try and merge my whole app into it, which won't be fun.

**Comment by alexfedoseev** [comment]
https://github.com/alexfedoseev/blog/blob/master/server.hot.js#L23

**Comment by reconstructions** [comment]
I am going to go ahead and close this, then push a branch with Bootstrap styles removed that breaks the hot reloading.  I don't think this is actionable without the context.
