### ISSUE TITLE
Bump Linter and Other Versions

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#398]
We need to bump [this line](https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/package.json#L108)

https://github.com/shakacode/style-guide-javascript

To v15.0.0:

```json
  "eslint-config-shakacode": "^14.1.1",
```

Maybe bump all npm dependencies?

**Comment by reconstructions** [comment]
@justin808, you can assign me this one if it helps, this introduces about about 29 linting errors, and I am working on fixing them now.

**Comment by reconstructions** [comment]
I bumped `eslint-config-shakacode` to version `16.0.0-rc.3` and tried some different approaches to fixing the various errors.  A few fixes were straight-forward, I am not sure about the rest.  

I already have a PR waiting for review, so I will sit on this one for now, let me know if it would prefer that I push this stuff into a new commit in the existing PR, or discuss details here first.

**Comment by justin808** [comment]
Please push to a new commit, @reconstructions. I just merged your other change.
