### ISSUE TITLE
Buildpack has gone missing?

### ISSUE THREAD

**Issue by chunky123** [shakacode/react-webpack-rails-tutorial#399]
Not sure if I am insane, but when I checked the buildpack for the `Rails Integration` section, I realized this doesn't publicly exist anymore: https://github.com/tempoautomation/heroku-buildpack-sourceversion.git

Does anyone have a backup version or know the contents of this buildpack? I'm using this on an app right now and I want to keep the same deployment process.

**Comment by jamesob** [comment]
We've recently cleared out a few forked repos which our organization no longer has any use for. The original source for the buildpack referenced by this repo's author is https://github.com/sreid/heroku-buildpack-sourceversion. I'd advise the author to update the README accordingly.

Be careful when referencing forks! The same kind of guarantees about maintenance and availability do not hold.

**Comment by chunky123** [comment]
Thanks! Using https://github.com/sreid/heroku-buildpack-sourceversion turned out great

**Comment by justin808** [comment]
@Judahmeek @udovenko @chunky123 Any chance that one of you can submit a doc PR on this? to https://github.com/shakacode/react_on_rails or here.

**Comment by chunky123** [comment]
I actually have a PR open to this repo here: https://github.com/shakacode/react-webpack-rails-tutorial/pull/400
