### ISSUE TITLE
Basic Demo Setup instruction lists wrong local host location

### ISSUE THREAD

**Issue by dvcarter** [shakacode/react-webpack-rails-tutorial#404]
The Basic Demo Setup documentation states the following instructions:

...
14. Open a browser tab to **http://localhost:3000** for the Rails app example with HOT RELOADING
15. Try Hot Reloading steps below!
16. foreman start -f Procfile.static
17. Open a browser tab to **http://localhost:3000** for the Rails app example.
18. When you make changes, you have to refresh the browser page.

In both cases (number 14 and number 17), the wrong default localhost is listed. The default localhost is actually **http://localhost:5000**

**Comment by justin808** [comment]
See my response: https://github.com/shakacode/react-webpack-rails-tutorial/pull/409#issuecomment-315683620
