### ISSUE TITLE
Any Instructions for Importing Images?

### ISSUE THREAD

**Issue by jesskrich** [shakacode/react-webpack-rails-tutorial#405]
I can't seem to find any. I've tried using file-loader/url-loader and does not throw me an error when I try to import, but when I try to render, I get a 404 (File Not Found). Can anyone provide some helpful resources? Been banging my head against the wall for hours.

**Comment by justin808** [comment]
If you want personalized help on this, please consider our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf).

Here's an example: https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/client/app/components/ImageExample/ImageExample.js
