### ISSUE TITLE
www.reactrails.com NOT using a production build of React

### ISSUE THREAD

**Issue by serodriguez68** [shakacode/react-webpack-rails-tutorial#406]
The production site is not using a production build (minified) version of react because the `build:production` script in the client/package.json file does not containt the `-p` flag for webpack. (I can tell because I'm using the react extension for Chrome).

To fix that, add the `-p` flag to the `build:production` script as shown next and re-deploy.
```
NODE_ENV=production webpack -p --config webpack.config.js
```
See [this issue](https://github.com/shakacode/react_on_rails/issues/875) and this [pull request](https://github.com/shakacode/react_on_rails/pull/895) for more information.

**Comment by justin808** [comment]
Was fixed a long time ago.
