### ISSUE TITLE
SCSS will not compile.

### ISSUE THREAD

**Issue by andrisole92** [shakacode/react-webpack-rails-tutorial#455]
Followed the tutorial on installation, created `HelloWorld.scss` in `HelloWorld/components`.

Have `import css from './HelloWorld.scss'. It will not work and `console.log(css)` gives an empty object. File's not empty 100%.

Does anyone have a solution?

**Comment by topstar26** [comment]
please install node-sass": "^4.7.2", "sass-loader": "^6.0.6"
npm run eject
npm install sass-loader node-sass --save-dev
run npm watch CSS 
It will be works
