### ISSUE TITLE
Webpack setup refinements

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#482]
We need to update

https://github.com/shakacode/react-webpack-rails-tutorial/tree/master/config/webpack

With the updates that have gone into:

https://github.com/shakacode/react_on_rails/tree/master/spec/dummy/config/webpack

and 

https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/config/webpacker.yml

Which are based on:

https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh

**Comment by jmtoporek** [comment]
If you still want help I'm willing to lend a hand

**Comment by ahangarha** [comment]
It seems files are updated.
If there is any particular changes that are left, please list them.
