### ISSUE TITLE
Tab "Simple React" behaves different. After adding second new comment it replaces with it the first one and inserts as second the last one

### ISSUE THREAD

**Issue by vtamara** [shakacode/react-webpack-rails-tutorial#494]
I reproduced this behaviour in Ubuntu 21.10 and ind adJ/OpenBSD 7.1a1.

I made a short video:
https://user-images.githubusercontent.com/701221/159935786-4815d38b-1fbf-428f-a744-3a715bf1c4e5.mp4

**Comment by vtamara** [comment]
It adds the comments in the database but doesn't present them right:

1. Just when user enter the tab it works fine one time
2. Second and nex times it will replace in the screen the first comment with the new one, and after it, it will insert the last one.

**Comment by vtamara** [comment]
Besides it doesn't present the footer of the other demos at the bottom of the page:
![image](https://user-images.githubusercontent.com/701221/160286796-cdf2f1f2-a91d-40af-9637-b040c8c82a4a.png)

**Comment by ahangarha** [comment]
I tested locally and online, and I didn't notice the issue.
It seems it is already resolved.
