### ISSUE TITLE
Provide example with react-rails

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#503]
We can allow an ENV value to switch between the two gems.

However, let's get dependencies updated first for this repo.

**Comment by ahangarha** [comment]
I spent some time on this feature. RWRT uses so many features from ReactOnRails that make it either impossible to pointless to add a switching feature to this project.

For such a switch, we need to implement the missing features (let's say, shared redux store) in this project. If it is one feature, it is understandable; but to add all ROR-specific features here, I see no point.

**Comment by justin808** [comment]
See https://github.com/shakacode/react-rails-example-app
