### ISSUE TITLE
Use `fetch` instead of `ajax` for HTTP requests

### ISSUE THREAD

**Issue by mapreal19** [shakacode/react-webpack-rails-tutorial#69]
`window.fetch` seems the way to go for http requests. 

Resources: 
  - https://github.com/github/fetch
  - http://mts.io/2015/04/08/webpack-shims-polyfills/

**Comment by alexfedoseev** [comment]
Pros:

* Proposed standard compatible.

Cons:

* Client-only -> Second lib for server-side calls.

**Comment by justin808** [comment]
@alexfedoseev If we assumed we would not need to make remote calls on the server (rending the JS using Rails engine), then is fetch a better choice?

**Comment by alexfedoseev** [comment]
Haha, I forgot that we're outside of Node here :sweat_smile: 
In this case `fetch` is perfectly ok.

**Comment by PlasticLizard** [comment]
Also, if you were on node, you could use [this](https://github.com/matthew-andrews/isomorphic-fetch)

**Comment by justin808** [comment]
@mapreal19 Could you take a try at this one and submit a PR?

**Comment by mapreal19** [comment]
@justin808 sure!

**Comment by justin808** [comment]
Check out https://github.com/shakacode/react_on_rails/issues/16#issuecomment-145159431
