### ISSUE TITLE
Demonstrate react-router + redux

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#72]
We can put in a sample of using react-router with redux. However, server side rendering may not work initially.

**Comment by josiasds** [comment]
@justin808 I've done an example of react-router and redux with @alexfedoseev. Any thoughts on this?

**Comment by muloka** [comment]
#128

**Comment by justin808** [comment]
![2015-11-06_12-56-36](https://cloud.githubusercontent.com/assets/1118459/11008533/0326b1b0-8486-11e5-874d-7a57bf608587.png)
