### ISSUE TITLE
Create a simple example of a React component with remote record to edit

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#77]
@geoffevason showed me an example of using the no-flux for the simple case of editing a single object with  remote call. I think this is a good example, and worth showing.

So long as the following conditions are met, it's OK to have the ajax call to save be at the top level of the component. The simple example is shown here, by the official [react docs](https://github.com/reactjs/react-tutorial/blob/master/public/scripts/example.js).

So I'd like to add a 3rd tab in the app showing "simple react". 

This will be a nice example to show off the [react_on_rails gem](https://github.com/shakacode/react_on_rails)

The special conditions for "no redux/flux required" would be:
1. The only input to the UI is user input or the return of the ajax call with validation messages or status.
2. We **LOCK** the UI while the AJAX flight is being sent.
3. We turn off async comment updates.

This is *super* simple if we're not displaying the comments list below. However, we can still do this with plain React so long as we disable proactive background fetching of the comments list. Thus, the comments list can be under the top level component, and it's ONLY updated a saved comment is confirmed to be saved at the server. When we get the confirmation, we insert the new comment to the top of the list.

Note, it's the aspect of having async, background comment refreshes that really justifies the use of a flux-type architecture to handle to ensure one way flow of the data.

Any volunteers to help with this? This would be a great learning exercise for React.

![cursor_and_railsreacttutorial](https://cloud.githubusercontent.com/assets/1118459/9698276/ad19d8cc-534a-11e5-8e57-ac053da1470a.png)

```javascript
var Comment = React.createClass({
  render: function() {
    var rawMarkup = marked(this.props.children.toString(), {sanitize: true});
    return (
      <div className="comment">
        <h2 className="commentAuthor">
          {this.props.author}
        </h2>
        <span dangerouslySetInnerHTML={{__html: rawMarkup}} />
      </div>
    );
  }
});

var CommentBox = React.createClass({
  loadCommentsFromServer: function() {
    $.ajax({
      url: this.props.url,
      dataType: 'json',
      cache: false,
      success: function(data) {
        this.setState({data: data});
      }.bind(this),
      error: function(xhr, status, err) {
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  },
  handleCommentSubmit: function(comment) {
    var comments = this.state.data;
    var newComments = comments.concat([comment]);
    this.setState({data: newComments});
    $.ajax({
      url: this.props.url,
      dataType: 'json',
      type: 'POST',
      data: comment,
      success: function(data) {
        this.setState({data: data});
      }.bind(this),
      error: function(xhr, status, err) {
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  },
  getInitialState: function() {
    return {data: []};
  },
  componentDidMount: function() {
    this.loadCommentsFromServer();
    setInterval(this.loadCommentsFromServer, this.props.pollInterval);
  },
  render: function() {
    return (
      <div className="commentBox">
        <h1>Comments</h1>
        <CommentList data={this.state.data} />
        <CommentForm onCommentSubmit={this.handleCommentSubmit} />
      </div>
    );
  }
});

var CommentList = React.createClass({
  render: function() {
    var commentNodes = this.props.data.map(function(comment, index) {
      return (
        // `key` is a React-specific concept and is not mandatory for the
        // purpose of this tutorial. if you're curious, see more here:
        // http://facebook.github.io/react/docs/multiple-components.html#dynamic-children
        <Comment author={comment.author} key={index}>
          {comment.text}
        </Comment>
      );
    });
    return (
      <div className="commentList">
        {commentNodes}
      </div>
    );
  }
});

var CommentForm = React.createClass({
  handleSubmit: function(e) {
    e.preventDefault();
    var author = React.findDOMNode(this.refs.author).value.trim();
    var text = React.findDOMNode(this.refs.text).value.trim();
    if (!text || !author) {
      return;
    }
    this.props.onCommentSubmit({author: author, text: text});
    React.findDOMNode(this.refs.author).value = '';
    React.findDOMNode(this.refs.text).value = '';
  },
  render: function() {
    return (
      <form className="commentForm" onSubmit={this.handleSubmit}>
        <input type="text" placeholder="Your name" ref="author" />
        <input type="text" placeholder="Say something..." ref="text" />
        <input type="submit" value="Post" />
      </form>
    );
  }
});

React.render(
  <CommentBox url="comments.json" pollInterval={2000} />,
  document.getElementById('content')
);
```

**Comment by geoffevason** [comment]
I'll find time to have a go at this this week

**Comment by josiasds** [comment]
This should enable the rendering for non-Redux components in the `react_on_rails` gem: https://github.com/shakacode/react_on_rails/pull/19

**Comment by josiasds** [comment]
PR #102 in progress!

**Comment by justin808** [comment]
Done!
