### ISSUE TITLE
Move to node 4.0.0

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#85]
https://nodejs.org/en/blog/release/v4.0.0/

> Node.js v4.0.0 contains V8 v4.5, the same version of V8 shipping with the Chrome web browser today. This brings with it many bonuses for Node.js users, most notably a raft of new ES6 features that are enabled by default including block scoping, classes, typed arrays (Node's Buffer is now backed by Uint8Array), generators, Promises, Symbols, template strings, collections (Map, Set, etc.) and, new to V8 v4.5, arrow functions.

Finally! We can fix server.js to be ES6.

**Comment by samnang** [comment]
We could wait a bit until some third parties start having it on their servers. For example, on CI.

**Comment by justin808** [comment]
@dylangrafmyre FYI -- closing. DONE.
