### ISSUE TITLE
imagePath option has been retired from node-sass

### ISSUE THREAD

**Issue by shunwen** [shakacode/react-webpack-rails-tutorial#86]
Ref. https://github.com/sass/node-sass/issues/702

In https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client%2Fbootstrap-sass.config.js#L13 the imagePath option is no longer available.

**Comment by justin808** [comment]
@shunwen Any recommendation on how we should handle this? @alexfedoseev, FYI

**Comment by shunwen** [comment]
@justin808 Hi, I don't know much about sass and assets, was on my way setting up deploy scripts and reviewing all options and found this one deprecated. I'll update here if I found additional info. Thanks for your tutorial by the way, it was really helpful. :+1:

**Comment by robwise** [comment]
@justin808 @alexfedoseev I believe we've already fixed this in our bootstrap integration by declaring its own helper: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/assets/stylesheets/_bootstrap-variables-customization.scss#L28

**Comment by justin808** [comment]
Per Rob's comment, this was fixed a while ago.
