### ISSUE TITLE
Remove bootstrap-sass-loader in favor of manually loading bootstrap

### ISSUE THREAD

**Issue by jbhatab** [shakacode/react-webpack-rails-tutorial#95]
Bootstrap-sass-loader autoloads bootstrap assets from the module so it isn't exposed at all for rails to pickup. This forces you to use the bootstrap-sass gem in addition to the npm module. If we just manually load all of the bootstrap from the npm module, then we can import that into the rails asset pipeline.

So all said and done you would basically move all of your assets to the client folder, manually setup bootstrap in your client folder, and form a new manifest file with everything in the js side. The rails manifest would turn into just requiring that client manifest and maybe some oddball things like bootstrap-sprockets just for the css. 

Are there any gotchas I'm missing?

**Comment by justin808** [comment]
Closing this for now. Feel free to re-open this later.

The main thing is to have a simple system that handles minification and fingerprinting.
